### ISSUE TITLE
RDS metrics from DbClusterIdentifier dimension are not available

### ISSUE THREAD

**Issue by raags** [ivx/yet-another-cloudwatch-exporter#113]
The RDS auroradb metrics for volumes are only available on the `DbClusterIdentifier`:
```
VolumeReadIOPs
VolumeWriteIOPs
VolumeBytesUsed
```
The current code enumerates the metrics with `DBInstanceIdentifier` and misses the above. Could we change this to do both? i.e. get metrics for the `cluster` +  `instance` ?

**Comment by raags** [comment]
Specifically, the `startingDimension` for rds has to be changed from Instance to Cluster identifier for these metrics to be visible, but its hardcoded to Instance here:

https://github.com/ivx/yet-another-cloudwatch-exporter/blob/fef89a6fc38d36ff5bb22553903480b4c7419bb8/aws_cloudwatch.go#L333-L334

One way could be to support a new field `baseDimension` that can be used to override this when required.

**Comment by bheight-Zymergen** [comment]
Are those even exposed through cloudwatch though?

https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Monitoring.html
```
The following metrics apply to an entire Aurora DB cluster, but are displayed only when viewing DB instances for an Aurora DB cluster in the Amazon RDS console:

VolumeBytesUsed

VolumeReadIOPs

VolumeWriteIOPs
```

It could just be me, but I also can't seem to extract that data with the aws cli tool. I can only see the data through the AWS Console UI.

**Comment by thomaspeitz** [comment]
This was fixed in a PR and just released. :)
