### ISSUE TITLE
Unable to get cloud watch metrics

### ISSUE THREAD

**Issue by anoopts** [ivx/yet-another-cloudwatch-exporter#116]
I have a very simple setup - 
Ec2 with golang version 1.13.3
yace version 0.14.5-alpha
config.yml :
discovery:
  exportedTagsOnMetrics:
    ec2:
      - Name
    ebs:
      - VolumeId
  jobs:
  - region: us-east-1
    type: "ec2"
    searchTags:
      - key: Name
        value: .*
    metrics:
      - name: CPUUtilization
        statistics:
        - 'Average'
        period: 60
        length: 600
        nilToZero: true
      - name: NetworkIn
        statistics:
        - 'Sum'
        period: 60
        length: 600
        nilToZero: true
      - name: StatusCheckFailed
        statistics:
        - 'Sum'
        period: 60
        length: 600
        nilToZero: true

I have enabled the IAM roles with required policies mentioned in the readme document and have tested for aws cli commands to list-metrics and get-metric-statistics and they work fine.

Even after enabling debug, I just see only these 2 lines in the logs
2019/10/30 20:49:17 Parse config.. 
2019/10/30 20:49:17 Startup completed 

and curl to metrics end-point gives
# HELP yace_cloudwatch_requests_total Help is not implemented yet. 
# TYPE yace_cloudwatch_requests_total counter 
yace_cloudwatch_requests_total 0 

Could you help me with enabling proper debugging and suggesting what I'm missing here? Thanks

**Comment by anoopts** [comment]
@thomaspeitz  Could you please help me out here.. I tried several versions and passing roleArn with no luck

**Comment by thomaspeitz** [comment]
@anoopts - Hey sorry currently moved into a new flat and not much support time for the project.

I am afraid that you wrote key and value instead of Key and Value is the problem. We should fix this. Yaml keys should start with lower case letters. Could you try this out please?

As there is no errors, i think permissions are working but the scraper just does not search anything.

**Comment by anoopts** [comment]
@thomaspeitz Thanks! really didn't know it was case sensitive.

**Comment by thomaspeitz** [comment]
Aweomse. Closing the issue now :)
