### ISSUE TITLE
Feature Request : Add Metrics from namespaces CWAgent, SES, Route53Resolver, TransitGateway, DX 

### ISSUE THREAD

**Issue by anoopts** [ivx/yet-another-cloudwatch-exporter#117]
We are using these services [ CWAgent, SES, Route53Resolver, TransitGateway, DX ] along with the ones that are already available. It would be great if you could add these for the automated discovery.

**Comment by thomaspeitz** [comment]
Could you please add one issue for every one. So people can work on it.

And please add informations about whether it is supported in this list (as it is a lot easier to implement if it is): https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/Welcome.html

Closing this big one.
