### ISSUE TITLE
I'll Using one cloudwaych-exporter.yml for AWS multi account Cloudwatch Monitoring is it possible ?

### ISSUE THREAD

**Issue by jaehyukryu** [ivx/yet-another-cloudwatch-exporter#125]
How to configuration one cloudwatch-exporter.yml for multi account cloudwatch monitoring?
is it possible ? 

 I Tried like a below Ex. (configure and command )
 but checked the localhost:9106, that result for just one account cloudwatch data. 

Ex. command )
java -jar target/cloudwatch_exporter-0.7.1-SNAPSHOT-jar-with-dependencies.jar 9106 test-cloudwatch.yml

   yml )
region: us-east-1
role_arn: arn:aws:iam::xxxxxxxxxxxxx:role/monitor
period_seconds: 300
range_seconds: 300
delay_seconds: 300
metrics:
 - aws_namespace: AWS/ELB
   aws_metric_name: UnHealthyHostCount
   aws_dimensions: [AvailabilityZone, LoadBalancerName]
   aws_dimension_select:
     LoadBalancerName: [ELB-PRD-ABC-TEST]
   aws_statistics: [Maximum]
   period_seconds: 300
   range_seconds: 300

 - aws_namespace: AWS/ELB
   aws_metric_name: HealthyHostCount
   aws_dimensions: [AvailabilityZone, LoadBalancerName]
   aws_dimension_select:
     LoadBalancerName: [ELB-PRD-ABC-TEST]
   aws_statistics: [Maximum]
   period_seconds: 300
   range_seconds: 300

region: us-east-1
role_arn: arn:aws:iam::zzzzzzzzzzzzz:role/monitor
period_seconds: 300
range_seconds: 300
delay_seconds: 300
metrics:
 - aws_namespace: AWS/ELB
   aws_metric_name: UnHealthyHostCount
   aws_dimensions: [AvailabilityZone, LoadBalancerName]
   aws_dimension_select:
     LoadBalancerName: [ELB-PRD-DEF-TEST]
   aws_statistics: [Maximum]
   period_seconds: 300
   range_seconds: 300

 - aws_namespace: AWS/ELB
   aws_metric_name: HealthyHostCount
   aws_dimensions: [AvailabilityZone, LoadBalancerName]
   aws_dimension_select:
     LoadBalancerName: [ELB-PRD-DEF-TEST]
   aws_statistics: [Maximum]
   period_seconds: 300
   range_seconds: 300

**Comment by bheight-Zymergen** [comment]
Based on your example command and the configuration you provided:

 I think you meant to ask this question on https://github.com/prometheus/cloudwatch_exporter
