### ISSUE TITLE
Feature request: add support for step functions

### ISSUE THREAD

**Issue by RolandOtta** [ivx/yet-another-cloudwatch-exporter#127]
we are currently using stepfunctions. it would be awesome to have support for step functions cw metrics => https://docs.aws.amazon.com/step-functions/latest/dg/procedure-cw-metrics.html

any chance that this will be implemented?

br,
roland

**Comment by thomaspeitz** [comment]
Implemented in https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/Welcome.html

**Comment by thomaspeitz** [comment]
Merged and released :)
