### ISSUE TITLE
Feature request: Decoupling scraping and serving metrics 

### ISSUE THREAD

**Issue by daviddetorres** [ivx/yet-another-cloudwatch-exporter#130]
Cloudwatch offers metrics with a 5 minutes granularity in the free tier. It would be interesting to decouple the gathering of metrics and the serving of those metrics. 

The exporter can scrap each 5 minutes (so it doesn't need to do in an intensive way, without risk of throlling the API and blocking it) and if the user/prometheus server has a higher scraping frequency it just serve the metrics gathered in background.

I can work in a PR that implements this.

**Comment by thomaspeitz** [comment]
Yeah had this on my list as well :) so would be happy to get a PR for that and merge for sure.

One thing i had in mind was to allow a base scrape interval and then override this per job if needed. Just some thoughts, accepting other ways as well.

**Comment by daviddetorres** [comment]
I'll try to work in this PR this week. Also, I saw that in case of throlling, the exporter exits. It would be interesting to treat this error and be able to recover from it, so the exporter will be able to continue working for future scrapings. I can add it to the PR.

**Comment by thomaspeitz** [comment]
Awesome looking forward for your PR - Please make both things as separate PRs it allows me to review a lot faster :)

**Comment by daviddetorres** [comment]
Different PRs. Great!

I will try to add also support for EKS in another PR.

**Comment by thomaspeitz** [comment]
This was merged. Thanks David!
