### ISSUE TITLE
Functionality: Validate YAML config

### ISSUE THREAD

**Issue by j-nix** [ivx/yet-another-cloudwatch-exporter#133]
It would be good to have a function that validates the existence of required fields within the config file, directly after it is unmarshalled.

We should be able to print helpful outputs explaining what is required or absent from config, along with any errors.

E.g:

One top level of either `discovery:` or `static:` should be found within the config file, then any sub-items should be evaluated - currently the binary will stay running with an invalid config file (until a request is made to cloudwatch)

**Comment by j-nix** [comment]
I've started working on this, so if anybody wants to help comment on here

**Comment by thomaspeitz** [comment]
Awesome looking forward to it :) Thanks!

**Comment by daviddetorres** [comment]
Hi @j-nix 
I was thinking on starting to work on the validation of the config file. 
Do you still want some help or should I start from scratch?

Maybe we can work in this issue at least the main check to perform in the config file (at least in the first iteration) before starting to code it.

**Comment by j-nix** [comment]
Hey @daviddetorres - great!

I actually haven't looked at this since I created this issue a few months ago so feel free to start from scratch - unsure if I got very far!

**Comment by daviddetorres** [comment]
Hi @j-nix and @thomaspeitz , 

I implemented some config validation in #195. Please, feel free to review and if you think that there is any other field that should be validated, I can add more checks.

**Comment by thomaspeitz** [comment]
<3 Merged and done.
