### ISSUE TITLE
many-to-many error

### ISSUE THREAD

**Issue by arnitolog** [ivx/yet-another-cloudwatch-exporter#14]
Sometimes after exporter's restart, I got an error: 
many-to-many matching not allowed: matching labels must be unique on one side
I guess it is due to one of the metrics in the query is missing at that moment. Do you have any ideas on how to handle this?
Here is the query which I use: 
aws_ec2_cpuutilization_average + on (name) group_left(tag_Product, tag_Name) aws_ec2_info

**Comment by tsupertramp** [comment]
Hey @arnitolog 

could it be that your exporter name is different every time you restart the exporter:
```ec2_info{instance="yace-some-id-which-changes-everytime:5000",job="yace",name="arn:test123```

Maybe if you are running on kubernetes and discovering the exporter through annotations for example.
Hostname changes everytime, so there is a short time where metrics for both exporter names exist:

You could fix this i think through matching metrics by exporter name:
```
aws_ec2_cpuutilization_average + on (name, instance) group_left(tag_Product, tag_Name) aws_ec2_info
```

Or you fix it by identifying the exporter always with the same name.

Does this already help you?

**Comment by arnitolog** [comment]
Yeah, that is exactly my case. And filtering on instance helped me. Thanks a lot for your help and for the great tool!

**Comment by tsupertramp** [comment]
Thanks for your feedback @arnitolog really appreciate that :) - Feel free to reopen if you still get stuck somewhere.
