### ISSUE TITLE
Feature Request: Support for Cloud Front using Discovery

### ISSUE THREAD

**Issue by mentos1386** [ivx/yet-another-cloudwatch-exporter#140]
As far as i can see, there is no support for Cloud Front using Discovery. This means that we have to manually add labels.

Are there any limitations that are preventing Cloud Front metrics from being used with Discovery?

**Comment by thomaspeitz** [comment]
https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/Welcome.html - It is in tagging API supported so should not be so difficult. Will try to do it next maintenance hour.

**Comment by mentos1386** [comment]
@thomaspeitz im playing with implementation https://github.com/ivx/yet-another-cloudwatch-exporter/compare/master...mentos1386:feat-add-cloud-front. What do you mean with "next maintenance hour"?

**Comment by thomaspeitz** [comment]
Will try to look over your implementation on friday.
