### ISSUE TITLE
EC2 instances without tags are absent if exportedTagsOnMetrics are set in discovery

### ISSUE THREAD

**Issue by LuciferInLove** [ivx/yet-another-cloudwatch-exporter#145]
Hello. I see only metrics for instances with any tags if exportedTagsOnMetrics are set in discovery, even though instance has no tags that are set in exportedTagsOnMetrics. Instances without tags are absent.

version: 0.16.0

**Comment by thomaspeitz** [comment]
@LuciferInLove - This should be fix. Could you retry?

**Comment by LuciferInLove** [comment]
@thomaspeitz, I've checked it on v0.19.1-alpha. Instances without tags are displayed (labels are `=""` as it should be), thank you.

**Comment by idanto** [comment]
Hi @LuciferInLove,

We have experienced the same issue for EBS metrics in the latest version `v0.24.0-alpha`.

can you please check if there wasn't any degradation? or point me to the fix you did?

**Comment by LuciferInLove** [comment]
Hello.
@idanto, I've checked instances without tags in v0.24.0-alpha recently, and these instances are shown. But I didn't check EBS without tags because we don't monitor EBS via yet-another-cloudwatch-exporter.

**Comment by idanto** [comment]
Thanks @LuciferInLove , I was wrong and thought you did the fix.

Maybe @thomaspeitz can help us with that.
