### ISSUE TITLE
superfluous response.WriteHeader

### ISSUE THREAD

**Issue by itatabitovski** [ivx/yet-another-cloudwatch-exporter#147]
I am running 0.15.0-alpha and seeing this error in the logs every couple of hours.

```
2020/04/08 17:00:14 http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.httpError (http.go:306)
```

**Comment by thomaspeitz** [comment]
Will update the client go lib for prometheus as soon as possible. - Maybe this fixes it.

We are not effected by this but thanks for reporting!

**Comment by Deepak1100** [comment]
I was having this issue. and it turns out that Prometheus was timing out.
so just increase scrape_timeout from Prometheus to maybe 20 sec(default scrape timeout is 10)

**Comment by thomaspeitz** [comment]
Closing this. Please tag me if there is still a problem after increasing the scrape_timeout

**Comment by itatabitovski** [comment]
What seems to have solved the issue was the upgrade of the prometheus golang client to 1.6.0.
