### ISSUE TITLE
RequestError: send request failed

### ISSUE THREAD

**Issue by nucl3arj4zz** [ivx/yet-another-cloudwatch-exporter#15]
Hey,
i've tried yace as an alternative to prom. Launch it in Docker container on AWS instance, while i get http response:
# HELP yace_cloudwatch_requests_total Help is not implemented yet.
# TYPE yace_cloudwatch_requests_total counter
yace_cloudwatch_requests_total 0

it still doesnt work, shows logs:

2018/09/25 05:50:41 Couldn't describe resources:  RequestError: send request failed
caused by: Post https://tagging.eu-west-1.amazonaws.com/: dial tcp 52.94.216.112:443: i/o timeout
2018/09/25 05:51:01 Couldn't describe resources:  RequestError: send request failed
caused by: Post https://tagging.eu-west-1.amazonaws.com/: dial tcp 52.94.220.75:443: i/o timeout
2018/09/25 05:51:21 Couldn't describe resources:  RequestError: send request failed
caused by: Post https://tagging.eu-west-1.amazonaws.com/: dial tcp 52.94.220.75:443: i/o timeout
2018/09/25 05:51:37 Couldn't describe resources:  RequestError: send request failed
caused by: Post https://tagging.eu-west-1.amazonaws.com/: dial tcp 52.94.220.75:443: i/o timeout
2018/09/25 05:51:41 Couldn't describe resources:  RequestError: send request failed
caused by: Post https://tagging.eu-west-1.amazonaws.com/: dial tcp 52.94.220.75:443: i/o timeout

i tried to start with a simple config, can you suggest what is wrong?
discovery:
  - region: eu-west-1
    type: "elb"
    searchTags:
      - Key: KubernetesCluster
        Value: kubernetes
    metrics:
      - name: HealthyHostCount
        statistics:
        - 'Minimum'
        period: 60
        length: 300
       - name: UnHealthyHostCount
        statistics:
        - 'Minimum'
        period: 60
        length: 300
      - name: RequestCount
        statistics:
        - 'Sum'
        period: 60
        length: 900
        nilToZero: true
      - name: Latency
        statistics:
        - 'Sum'
        period: 60
        length: 900
        nilToZero: true

**Comment by tsupertramp** [comment]
Hey @nucl3arj4zz is this still a problem.

Sorry for late reply spent some vacation in Portugal :)

This looks like your instance can not reach aws servers. Could think of a firewall problem. Are you using maybe something like https://github.com/jtblin/kube2iam 

If this is just a simple server, then maybe you forget to add egress security group rules to reach aws servers?

Did you add an iam role to your server with following policy? https://github.com/ivx/yet-another-cloudwatch-exporter/blob/master/README.md#iam

Greetings, Thomas

**Comment by tsupertramp** [comment]
Closing this. Feel free to reopen if you still have problems :)
