### ISSUE TITLE
S3, RDS metrics missing with 0.18.0 binary build?

### ISSUE THREAD

**Issue by pocketcalculator** [ivx/yet-another-cloudwatch-exporter#162]
I'm trying to determine why I'm missing data for S3 and RDS.  EC2 and EBS metrics look good.

<pre>
discovery:
  jobs:
    - type: ebs
      region: us-east-1
      enableMetricData: true
      metrics:
        - name: VolumeReadBytes
          statistics:
            - Sum
          period: 300
          length: 3600
        - name: VolumeWriteBytes
          statistics:
            - Sum
          period: 300
          length: 3600
        - name: VolumeReadOps
          statistics:
            - Sum
          period: 300
          length: 3600
        - name: VolumeWriteOps
          statistics:
            - Sum
          period: 300
          length: 3600
        - name: VolumeTotalReadTime
          statistics:
            - Sum
          period: 300
          length: 3600
        - name: VolumeTotalWriteTime
          statistics:
            - Sum
          period: 300
          length: 3600
        - name: VolumeIdleTime
          statistics:
            - Sum
          period: 300
          length: 3600
    - type: ec2
      region: us-east-1
      enableMetricData: true
      metrics:
        - name: CPUUtilization
          statistics:
            - Average
          period: 300
          length: 3600
        - name: DiskReadOps
          statistics:
            - Average
          period: 300
          length: 3600
        - name: DiskWriteOps
          statistics:
            - Average
          period: 300
          length: 3600
        - name: NetworkIn
          statistics:
            - Average
          period: 300
          length: 3600
        - name: NetworkOut
          statistics:
            - Average
          period: 300
          length: 3600
    - type: rds
      region: us-east-1
      enableMetricData: true
      metrics:
        - name: CPUUtilization
          statistics:
            - Average
          period: 300
          length: 3600
    - type: s3
      region: us-east-1
      enableMetricData: true
      metrics:
        - name: NumberOfObjects
          statistics:
            - Average
          period: 300
          length: 3600
        - name: BucketSizeBytes
          statistics:
            - Average
          period: 300
          length: 3600
</pre>

**Comment by chris-b2c2** [comment]
Breaking change, `region` became `regions`.

https://github.com/ivx/yet-another-cloudwatch-exporter/blob/master/CHANGELOG.md#0180-alpha

**Comment by thomaspeitz** [comment]
Please retry with regions as stated in the CHANGELOG, tag me if not solved. I would reopen then. Else i keep it closed.

**Comment by pocketcalculator** [comment]
Thanks, @thomaspeitz .  Even with regions replacing region, I'm seeing metrics only for EC2 and EBS.  No data for RDS, S3 or Lambda.
