### ISSUE TITLE
Support for multiple config YAML 

### ISSUE THREAD

**Issue by shomeprasanjit** [ivx/yet-another-cloudwatch-exporter#163]
Hello , Would like to have metrics pulled from multiple AWS accounts but will send it over to single specific metrics endpoint port. 

currently the last config file is picked up while rest is ignored, silently. shouldn't it be better to have a warning/error message print out ?

```
bin/yace -debug -config.file config/account1_config.yml -config.file config/cross_account_1_config.yml -config.file config/cross_account_2_config.yml -listen-address :443 
```

So that data from all accounts can be scraped using ```<hostname or ELB name>:<port_number>/metrics``` endpoint.

we are currently planning to host this in ec2 but open to plans to migrate it to docker or k8s pods.

**Comment by thomaspeitz** [comment]
Please concenate your yaml files through your own script. We won't support multiple config files.

Multiple aws accounts are now supported. Closing this here.

Greetings, Thomas :)
