### ISSUE TITLE
Feature Request: SnakeCase and Lowercase label name

### ISSUE THREAD

**Issue by goya** [ivx/yet-another-cloudwatch-exporter#166]
This might get political.  I'm wondering what people's thoughts are on:
- lowercasing all labels names
- snakeCasing all label names

If we want to do this, do we:
1. make it default
2. make it an option, default yes
3. make it an option, default no

**Comment by goya** [comment]
i vote 2!

**Comment by goya** [comment]
i vote 1. it seems to be a convention, and it is used for the metric name.

**Comment by thomaspeitz** [comment]
As aws supports tags e.g. "Environment" and "environment" - I am against it but I keep it open maybe a lot of other users want to see it then we can think of an solution.

**Comment by daviddetorres** [comment]
We should be careful while changing names of the labels. This can affect both dashboards and alerts that users have already configured and in production. 

If any change is done, my opinion is to make it optional, and at least for some versions not to do it by default so users can have some time to adapt their visualizations and alerts.

**Comment by goya** [comment]
i vote 3 now!

**Comment by thomaspeitz** [comment]
Was merged and released :)
