### ISSUE TITLE
Allow no prefix option

### ISSUE THREAD

**Issue by goya** [ivx/yet-another-cloudwatch-exporter#167]
Should we allow people to skip the prefixes on label names?

eg. `custom_tag_`, `tag_`, `dimensions_`

Should we:
* add option (maybe to a new `options` key in the yaml), default `noPrefixes=false`

**NB.**  it would have to be highlighted that this will override labels of the same name, if say a tag has the same name as the dimension name etc.

**Comment by thomaspeitz** [comment]
No, lets keep those prefixes please. It shows easily where it comes from.

Removing those would introduce a lot of new bugs where things are overwritten.
