### ISSUE TITLE
Feature: Add more debugging log output

### ISSUE THREAD

**Issue by dudicoco** [ivx/yet-another-cloudwatch-exporter#183]
Hi,

Current logs with `debug=false` are not verify useful:
```
{"level":"info","msg":"Parse config..","time":"2020-06-29T11:52:23Z"}
{"level":"info","msg":"Startup completed","time":"2020-06-29T11:52:23Z"}
```

Is it possible to add some more meaningful logs? Such as the arguments used to start the process, and log line per scrape start/finish + errors?

Thanks!

**Comment by daviddetorres** [comment]
Hi, 

Apart from improving logs when `debug=false`, what are your thoughts about making different log levels for the exporter and for the CloudWatch API? 

The motivation is that sometimes, you want to see the debug log of the exporter and CloudWatch API can generate lots of logs that makes it more difficult to trace exporter specific problems. 

Other option can be to set debug as level, not as a boolean. 
- info
- debug: application debug
- trace: application + CloudWatch API


Another open question: What `info` messages would be interesting? (In a not-troubleshooting scenario).
- Flags of the start up
- Config file read correctly / nº jobs
- Scrape started/ended
- Nº of resources / nº metrics of the scrape?
- Errors / warnings

**Comment by dudicoco** [comment]
@daviddetorres I like all of your ideas! :)

**Comment by thomaspeitz** [comment]
We added those. Please reopen new issueS for every feature you would like to see in the exporter log lines. Thank you.
