### ISSUE TITLE
Resources with no tags are not included in the metrics

### ISSUE THREAD

**Issue by daviddetorres** [ivx/yet-another-cloudwatch-exporter#185]
I don't know if this is a bug or a feature... but:

**Resources with no tags are not included in the metrics.** 

Why does this happen?
- While scraping data, first a list of resources is asked with the GetResourcesPagesWithContext API call. This returns the resources with tags... but not the resources that have no tags. 
- After getting the resources, a list of dimensions for the metric is asked. 
- Finally, the for every resource, looks in the dimensions list to see if it exists and ask for those metrics. 

So, with this, if a resource is not listed in the first call, it will not be asked for metrics. 

Solution?
- First, document that all resources that should be monitored has to have at least 1 tag. 
- Then... ideas? Do monitorable resources always have tags? Should it be asked as a requisite?
- Is there a possible configuration that get all the resources, including the untagged ones?

**Comment by thomaspeitz** [comment]
Hey David,

i am open to an update of docs but i see it as obvious that tags are needed.
We won't add a "collect all" functionality. AWS Tags should be used to monitor. This reduces the api calls
and users (hopefully) only collect metrics they need.
This is a hard prerequisite of this exporter.

Closing this but open to contribution of docs.

**Comment by daviddetorres** [comment]
I think the same. That is why I said at the beginning maybe it was a feature. 
Thanks!
