### ISSUE TITLE
Auto discovery : Custom-Metrics

### ISSUE THREAD

**Issue by ebersb** [ivx/yet-another-cloudwatch-exporter#190]
Hi,

AWS also supports custom metrics and we use this to write our own metrics to CloudWatch.
The metrics with static dimension works fine to export via statics configuration.

For some custom metrics, with a ‘binded’ resource (like ec2:InstanceId) in the dimension, I can’t fetch and export them.

I’m looking for an export feature, like the services from the auto discovery. Where I could set my custom namespace and the baseDimension, like “InstanceId” and “instance/“ or using a service name as a base definition (ec2, elb …).

I walk through the code and it’s looks for a big code change :-(
If you like this feature, how could we proceed and how should this looks like?

Link:
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/publishingMetrics.html

Metric-Sample:
```
Namespace: MyCustomMetric
Dimensions:
	name: component
	value: comp-A
	name: tier
	value: stage
	name: InstanceId
	value: i-xxxxxxxxx
Metric: myMetric
	Average : 1
	Maximum : 3

```

**Comment by thomaspeitz** [comment]
Closing in favour of https://github.com/ivx/yet-another-cloudwatch-exporter/issues/325

We won't support it generically but via http. This is not something I will work on but I accept PRs.

Greetings, Thomas
