### ISSUE TITLE
YACE with Prometheus using role assumption

### ISSUE THREAD

**Issue by sujaiyshivakumar** [ivx/yet-another-cloudwatch-exporter#193]
We are trying to build a monitoring solution with Prometheus in our Monitoring AWS account that needs to pull data from CloudWatch in a sub-account. Prometheus is installed and running on an Ubuntu EC2 instance with the following config - 

global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m
scrape_configs:
  - job_name: 'yace'
    honor_labels: true
    static_configs:
      - targets: ['localhost:5000']

YACE is up and running with Docker on port 5000 with the following config - 
discovery:
  exportedTagsOnMetrics:
    ebs: #EBS VOLUME
      - VolumeId
    alb: #APPLICATION LOAD BALANCER
      - Name    
  jobs:
  - type: ebs
    roleArn: arn:aws:iam::SUBACCOUNTNUMBER:role/iam-role
    regions:
      - us-east-1
    searchTags:
      - Key: monitor
        Value: true
    metrics:
      - name: VolumeReadOps
        statistics:
        - Sum
        period: 300
        length: 3600
      - name: VolumeWriteOps
        statistics:
        - Sum
        period: 300
        length: 3600
  
  - type: alb
    roleArn: arn:aws:iam::SUBACCOUNTNUMBER:role:role/iam-role
    regions:
      - us-east-1
    searchTags:
      - Key: telemethus-monitor
        Value: true
    metrics:
      - name: HTTPCode_ELB_4XX_Count
        statistics:
        - Sum
        period: 300
        length: 3600
        nilToZero: true

The EC2 instance that Prometheus is installed in has an IAM role attached that can assume the sub-account IAM role because of the following trust relationship - 
arn:aws:iam::MONITORACCOUNTNUMBER:role/ROLE-NAME-ATTACHED-TO-PROMETHEUS-EC2

Troubleshooting results - 
1) I see the target, YACE, as Registered and Up in the Prometheus dashboard. but domainname/metrics shows no metrics from the EBS volume or the ALB. 
2) docker logs -f containerID - Does not show any errors, but "Parse config..." and "Startup completed"
3) Confirmed that the EBS volumes and the ALBs are tagged appropriately as well. 

Any pointers on what could be the issue?

**Comment by singhjagmohan1000** [comment]
If the instance has already IAM role attached no need to define `roleArn: arn:aws:iam::SUBACCOUNTNUMBER:role:role/iam-role`.

**Comment by cloud303-sshivakumar** [comment]
@singhjagmohan1000 The IAM role attached to the instance is not the same as the SubAccount IAM Role and the IAM role attached to the instance does not have permissions in the other account to retrieve CloudWatch metrics, only has permissions to assume the SubAccount IAM Role, if that makes sense.

**Comment by sujaiyshivakumar** [comment]
@singhjagmohan1000  The IAM role attached to the instance is not the same as the SubAccount IAM Role and the IAM role attached to the instance does not have permissions in the other account to retrieve CloudWatch metrics, only has permissions to assume the SubAccount IAM Role, if that makes sense.

**Comment by sujaiyshivakumar** [comment]
Hola! Any updates?

**Comment by josephreynolds** [comment]
@sujaiyshivakumar It would be more clear with the actual policies, but if yace is running in account A, on the Prometheus ec2 instance, and you're reading the metrics from a different account, I would expect it to look somethings like this:

`iam_role_yace` has policy `iam_policy_assume_cross` , which grants it `assume role` to role in `iam_acct_a_cross_query`

 `iam_acct_a_cross_query` has a policy which provides the appropriate permissions required, as if you were running in the subaccount , such as `tag:GetResources` and `"cloudwatch:ListMetrics",  "cloudwatch:GetMetricStatistics"`.

I hope this helps guide you towards a solution.

**Comment by thomaspeitz** [comment]
This should work like @josephreynolds describes. Closing it.
