### ISSUE TITLE
Add rounding to current time before making a CloudWatch API call

### ISSUE THREAD

**Issue by dudicoco** [ivx/yet-another-cloudwatch-exporter#203]
The CloudWatch API rounds down the seconds for start time and end time in the request, this can introduce one extra minute of delay if the scraping always takes place closer to the end of the minute - 19:15:57 will be rounded down to 19:15:00. I suggest rounding up or down the current time before each request (19:15:28 will be rounded down, 19:15:32 will be rounded up).

**Comment by thomaspeitz** [comment]
This was fixed in some releases ago and can be configured in the newest release.

Greetings, Thomas
