### ISSUE TITLE
RDS returns nothing - EC2 works fine

### ISSUE THREAD

**Issue by Thomaszahradnik** [ivx/yet-another-cloudwatch-exporter#215]
Regardless of the time period and length, rds just never returns anything

`discovery:
  exportedTagsOnMetrics:
    rds:
      - Name
  jobs:
  - type: rds
    enableMetricData: true
    regions:
      - af-south-1
    metrics:
      - name: CPUUtilization
        statistics:
        - 'Maximum'
        period: 300
        length: 1200

`

**Comment by rsvas** [comment]
I am facing the same/similar issue on RDS DB instances metrics, they are not visible through YACE when there is no tag applied on the AWS RDS DB instance level.

After I am adding a tag on RDS DB instance in AWS: something like: "Name: db-name", YACE started scraping this DB instance metrics.

So question is: is a minimum of one tag needs to be applied on AWS RDS DB instance in-order for YACE to scrape it's metrics?

YACE config looks like below:

discovery:
  jobs:
  - type: rds
    roleArns:
      - "arn:aws:iam::111111111111:role/iam-role"
    regions:
      - us-west-2
    period: 300
    length: 900
    delay: 120
    additionalDimensions:
     - DBClusterIdentifier
    metrics:
      - name: CPUUtilization
        statistics: ['Average', 'Minimum', 'Maximum']
        nilToZero: true

Any input on this is really appreciated! if this is the defect, can it be please addressed?

**Comment by newbootz** [comment]
@rsvas I ran into this same issue with a similar config to yours.

The default dimension is "DBInstanceIdentifier", so when I leave out the dimensions conifg part out, metrics work for that dimension only. I also tried to specify "DBClusterIdentifier", "Role" and even "EngineName" but no luck getting additional dimensions to work for rds. 

 I believe there might be something missing in the logic for the rds "additionalDimensions" config option.

**Comment by newbootz** [comment]
Looking more into it, it appears to be a known issue:

https://github.com/ivx/yet-another-cloudwatch-exporter/issues/113

**Comment by thomaspeitz** [comment]
This should be fixed by newest release. Please comment if not. Closing it.

**Comment by james-emerton** [comment]
I am seeing the behaviour described in the ticket with v0.28.0-alpha. RDS instances without tags are ignored, but adding any tag to the instance causes it to appear in the metrics.
