### ISSUE TITLE
"<" and ">" in Custom Metrics are not sanitized

### ISSUE THREAD

**Issue by ibexa-yuna** [ivx/yet-another-cloudwatch-exporter#217]
Hi,

I'm using Custom Metrics in CloudWatch and my application generates aggregate metric using the following naming format:

`application:<all-nodes>:metricName`

If I try exporting this static metrics I'm getting an error:
`panic: descriptor Desc{fqName: "aws_mycustonnamespace_myapplication_<all_nodes>_num_requests_average", help: "Help is not implemented yet.", constLabels: {}, variableLabels: []} is invalid: "aws_mycustonnamespace_myapplication_<all_nodes>_num_requests_average" is not a valid metric name`

Config snippet:
```static:
  - namespace: mycustomnamespace
    name: must_be_set
    regions:
      - eu-west-1
    metrics:
      - name: myapplication:<all-nodes>:NumRequests
        statistics:
        - Average
        period: 60
        length: 300```

Stacktrace:
```
goroutine 17 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc0000a4d70, 0xc0004ebf18, 0x1, 0x1)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.7.0/prometheus/registry.go:401 +0xad
main.updateMetrics(0xc0000a4d70)
	/github/workspace/main.go:87 +0x2ad
main.main.func1(0xc00023e0d0)
	/github/workspace/main.go:123 +0xbe
created by main.main
	/github/workspace/main.go:120 +0x490
```

Most probably, this function should be expanded to escape "<" and ">" chars:
https://github.com/ivx/yet-another-cloudwatch-exporter/blob/v0.19.1-alpha/prometheus.go#L132

**Comment by thomaspeitz** [comment]
I think the problem is that prometheus does not support `<` and `>`. I will replace it with underscore and you can verify if it works now.

**Comment by thomaspeitz** [comment]
Released,

does it work? @ibexa-yuna

**Comment by ibexa-yuna** [comment]
It does work. Thank you.

mycustomnamespace_myapplication__all_nodes__numrequests
