### ISSUE TITLE
Add discovery through tags for AWS VPN

### ISSUE THREAD

**Issue by AndrewChubatiuk** [ivx/yet-another-cloudwatch-exporter#22]
Used prometheus/cloudwatch_exporter before and occasionally found this project. Going to use it but need a Cloudwatch VPN metrics support

**Comment by tsupertramp** [comment]
Thanks a lot @AndrewChubatiuk :) 

Will look through it / merge on friday :)

**Comment by tsupertramp** [comment]
Merged. Thanks for your work!
