### ISSUE TITLE
Access using access key and secret key

### ISSUE THREAD

**Issue by TidC921** [ivx/yet-another-cloudwatch-exporter#229]
I was wondering if it was possible to use this exporter using aws_access_key_id and aws_secret_access_key rather than using a roleArn? I had this working with the prom/cloudwatch exporter but get the following when trying this for yace with the running locally command in the README.md, using .aws/credentials

`"level":"info","msg":"Couldn't describe resources for region eu-west-1: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors\n"`

**Comment by cgstag** [comment]
I had this problem on my first try : this is likely a lack of permissions :
1) Make sure if you use MFA for AWS to copy your temp-credentials
2) Make sure your credentials files is not a symlink (copy the content to a new file to make sure) and has enough permission `chmod 664 credentials`

Hope it helps

**Comment by alertedsnake** [comment]
I can confirm it works using the environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.

**Comment by TidC921** [comment]
Thank you - I also have got this working now :)
