### ISSUE TITLE
Panic when trying to access API Gateway resources without metrics

### ISSUE THREAD

**Issue by calvinbui** [ivx/yet-another-cloudwatch-exporter#237]
I don't have the exact panic message anymore but it was a nil/invalid pointer from this line: https://github.com/ivx/yet-another-cloudwatch-exporter/blob/v0.20.0-alpha/aws_cloudwatch.go#L513

I deleted API GWs without the 'dashboard' option and it solved the issue.

![Screen Shot 2020-08-20 at 12 55 04 pm](https://user-images.githubusercontent.com/3604363/90712312-16bc0e00-e2e6-11ea-99c9-982d2f3d723c.png)

API GWs with the 'dashboard' option but without any metrics were OK and didn't cause issues.

![Screen Shot 2020-08-20 at 12 55 16 pm](https://user-images.githubusercontent.com/3604363/90712316-1885d180-e2e6-11ea-95db-a467d8d13cee.png)

**Comment by udhos** [comment]
Can you check if the panic happens by building from master?

This fix https://github.com/ivx/yet-another-cloudwatch-exporter/pull/247 might have corrected it.

**Comment by thomaspeitz** [comment]
This is still a problem @calvinbui ?

**Comment by calvinbui** [comment]
I'm not too sure as I dont have anything to test with.

Closing.
