### ISSUE TITLE
Tags on individual metrics

### ISSUE THREAD

**Issue by nhinds** [ivx/yet-another-cloudwatch-exporter#24]
Could yace be modified to add tags as labels on the individual metrics instead of (or as well as) the `aws_<service>_info` meta-metric?

For yace, graphing e.g. the request rate for all ELBs in a service would currently look like:
```
rate(aws_elb_requestcount_sum[5m]) + on (name) group_left(tag_kubernetes_io_service_name) aws_elb_info{tag_service="something"}
```
This is quite a long query to do filtering on a tag, and I expect that once there's a large amount of cloudwatch metrics ingested into Prometheus, this will be much slower than a query like `rate(aws_elb_requestcount_sum{tag_service="something"}[5m])`, since Prometheus will calculate the 5-minute rate for every ELB in its database before filtering down to a specific service.

(We had previously been using a `machine_info` metric similar to the `aws_<service>_info` metric for a while, but noticed there were performance problems when trying to graph metrics filtering by tags - e.g. graphing `rate(node_vmstat_pgpgin{service="something",otherlabel="somethingelse"}[5m])` is an order of magnitude or 2 faster than graphing `rate(node_vmstat_pgpgin[5m]) * on (instance) machine_info{service="something",otherlabel="somethingelse"}`. It seems like when Prometheus is asked to join 2 metrics and only filter one of them, it isn't smart enough to optimise that join and it ends up reading data for every metric that exists for the unfiltered side.)

I could solve this with a recording rule in Prometheus for each metric that yace returns that joins the metric to the `aws_<service>_info` metric, but it would be cleaner if the metrics started out with the labels.

Is this a change you'd be interested in?

**Comment by tsupertramp** [comment]
Its not difficult to implement and it was my initial plan.

During my research to write the exporter, i spoke with a very helpful prometheus contributor. He gave me a lot of tipps. One of them was to not do it that way.

"CAUTION: Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values." - https://prometheus.io/docs/practices/naming/

So lets make an example of your idea vs the current implementation of this exporter:

Example:
- You are monitoring 3x elbs with 10x metrics => 30x cloudwatch Metics + 3x aws info metrics
- You add a 4x elb to your monitoring which has a new tag.

Current implementation:
- There are now 4x new aws info metrics. As the new tag need to be added to all info metrics. As one metric should always have the same labels.
- There are 10x new cloudwatch metrics.

Your idea:
- 40x new cloudwatch metrics as every metric needs consistent labels, therefore all metrics must be changed.

For me it feels like that tags are not changed very frequently. What is your opinion about it after hearing the reason why it was done that way?

**Comment by nhinds** [comment]
Thanks for the background. I agree that adding new tags on one ELB shouldn't cause the others to turn into new metrics, that does sound like it would cause issues.

Since each tag is associated with a resource in AWS, I don't think tag values fall into the "unbounded sets of values" category - but you're right, it would be unwise to add all of the tags to each metric and blow out the metrics storage.

In my case I only really filter on 2 or 3 tags across my infrastructure, which identify the group/service the resources belong to. Would having configuration for a list of tags to associate with actual metrics make sense instead of all tags? That way adding extra ELBs with new tags won't cause the other ELB metrics to change, just the AWS info metrics, but Prometheus can still filter metrics by those tags.

**Comment by tsupertramp** [comment]
Thats a nice idea i like that. @nhinds 

Maybe something like that in the config file. What do you think @nhinds
``` yaml
staticTags:
  ec2:
    - Name
    - Environment
  rds:
    - Name
    - CostLocation
discovery:
 - region: eu-west-1
   type: "ec2"
   searchTags:
     - Key: Name
       Value: Jenkins.*
   metrics:
     - name: CPUUtilization
       statistics:
         - 'Maximum'
       period: 6000
       length: 6000
```

**Comment by tsupertramp** [comment]
This makes sense for our company as well. Nice fix for the issue. Will try to implement this today or next friday. Having another issue i want to implement first, lets see, how it works out.

**Comment by nhinds** [comment]
I've given this a go in #25

**Comment by nhinds** [comment]
Ah oops, didn't intend to duplicate work -- just hadn't seen any activity and had some spare time. Feel free to close mine if you like.

**Comment by tsupertramp** [comment]
@nhinds - Yeah already started with the topic last friday and should have told you. Sorry!

But i love all your contributions. Very happy about it!
