### ISSUE TITLE
Is the exporter production ready?

### ISSUE THREAD

**Issue by Yagyansh** [ivx/yet-another-cloudwatch-exporter#243]
I have read a lot about this exporter, and have been quite impressed by the optimizations and fixes that have been made by Sysdig. But, is the exporter totally production-ready and safe to use in production environment?
Initially, I'll only pull ELB metrics and then move to capture data from other managed services.

**Comment by thomaspeitz** [comment]
We are not stable yet. - We change a lot and errors can happen.

We are using yace since a year to watch our production environment and were not disappointed yet.
