### ISSUE TITLE
Issue using yace for kinesis metrics without docker

### ISSUE THREAD

**Issue by suman-aella** [ivx/yet-another-cloudwatch-exporter#254]
I am trying to run Yace as a binary outside the container to get my kinesis metrics

./yace --config.file=/home/suman/yace/config.yml

It is not able to get any kinesis metrics with it.

When debugged it fetches the list metrics details but no the metrics data

```
2020/09/24 12:40:56 DEBUG: Request monitoring/ListMetrics Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1^M
Host: monitoring.us-east-1.amazonaws.com^M
.
.
Action=ListMetrics&MetricName=GetRecords.Success&Namespace=AWS%2FKinesis&Version=2010-08-01
-----------------------------------------------------
2020/09/24 12:40:56 DEBUG: Response monitoring/ListMetrics Details:
---[ RESPONSE ]--------------------------------------
.
.
2020/09/24 12:40:56 <ListMetricsResponse xmlns="http://monitoring.amazonaws.com/doc/2010-08-01/">
  <ListMetricsResult>
    <Metrics>
      <member>
        <Namespace>AWS/Kinesis</Namespace>
        <MetricName>GetRecords.Success</MetricName>

.
.
```

In the config I gave the metrics info I needed

```
discovery:
  jobs:
  - type: kinesis
    regions:
      - us-east-1
    enableMetricData: true
    searchTags:
     - Key: Name
       Value: .*
    metrics:
      - name: GetRecords.Success
        statistics:
        - Sum
        - Average
        period: 10
        length: 60`

**Comment by suman-aella** [comment]
When I debug more it shows that AWS GetResources where fetching empty result

{"level":"info","msg":"Input params for GetResourcesPagesWithContext {\n  ResourceTypeFilters: [\"kinesis:stream\"]\n} \n","time":"2020-09-25T08:58:08Z"}
{"level":"info","msg":"page.ResourceTagMappingList [] \n","time":"2020-09-25T08:58:08Z"}

Any reason why it is happening so?

**Comment by singhjagmohan1000** [comment]
@suman-aella Make sure resources are tagged in AWS, I have seen similar behavior in SQS. When tags are missing it list metrics but not get metric data

**Comment by suman-aella** [comment]
> @suman-aella Make sure resources are tagged in AWS, I have seen similar behavior in SQS. When tags are missing it list metrics but not get metric data

@singhjagmohan1000 Yes with tagging I am getting the metrics but is it the right way? I mean to get metrics only for tagged resources.

**Comment by singhjagmohan1000** [comment]
@suman-aella This is how the exporter is designed. It will get metrics for tagged resources only. I was able to get metrics for untagged SQS metrics, via simple workaround. To make that change generic, it will need lot of work. I do not know how useful that be. I think its better to have at-least one tag. We are also working on tagging resources, so that we should face the issue of missing metrics.

**Comment by thomaspeitz** [comment]
Yes, it is a basic concept that resources are needed to be tagged. It is not intended by me that this exporter will support unttaged resouces.

Greetings, Thomas
