### ISSUE TITLE
nilToZero issue

### ISSUE THREAD

**Issue by arnitolog** [ivx/yet-another-cloudwatch-exporter#259]
Hello, 
I think this is not the correct way to report 0 in case when AWS doesn't provide a response.
We collect metrics for RDS EBS BurstBalance. And for stopped RDS instances, AWS doesn't provide such metrics. with nelToZero option we will get 0. In this situation alert will be triggered, because we definitely want to know when our BurstBalance is 0.
At the same time without nilToZero option, it always reports 100% which is ok for stopped instances, but not good if BurstBalance is 0 and then, for some reason data is absent.
I think more relevant here to report NaN in case when YACE can get an answer from AWS

**Comment by arnitolog** [comment]
created https://github.com/ivx/yet-another-cloudwatch-exporter/pull/265 for that

**Comment by thomaspeitz** [comment]
Closed. Thanks for the issue and the fix <3
