### ISSUE TITLE
_info metric is gone

### ISSUE THREAD

**Issue by sweepkim** [ivx/yet-another-cloudwatch-exporter#271]
Hi, 

From 0.21.0-alpha (till 0.23.0-alpha), _info metric has just 0 like below.
```
aws_ecs_info 0
aws_cf_info 0
aws_ec_info 0
aws_ecs_containerinsights_info 0
aws_ecs_svc_info 0
```

0.20.0-alpha shows metric with some values with same config file.

Is there any changes ?

thanks in advance.

**Comment by PaulRudin** [comment]
I see the same thing for aws_s3_info

**Comment by thomaspeitz** [comment]
Will be released this week.

**Comment by sweepkim** [comment]
> Will be released this week.

It's good news for me and thanks for your reply.

**Comment by thomaspeitz** [comment]
Should be resolved by now. Closing it.

Thanks for your patience.
