### ISSUE TITLE
New Discovery Type for yace

### ISSUE THREAD

**Issue by wutianchen** [ivx/yet-another-cloudwatch-exporter#28]
We forked yace in our internal project. Since more discovery type is required in our use case, we have implemented type sqs. So the following questions in our mind 

1) would that be proper to contribute our work to this project ?
2) is that correct only "AWS Resource Group Tagging" supported services (https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/Welcome.html) can be added to supported services list ?

thanks a lot

**Comment by tsupertramp** [comment]
Hey @wutianchen - We are always happy about contributions. So yeah just make a PR and lets discuss it.

Till now only service discovery is supported for resources which can be find by tagging api. But i would be interested in a PR which would support a a service which is not included in this api. About which service are you talking, as SQS is supported (https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/Welcome.html).

Greetings, Thomas

**Comment by wutianchen** [comment]
Hi @tsupertramp  thanks for the feedback. interesting idea.
The services we are using and not supported yet by resource group api is for example, ecs, iot etc.

I do not know if it is possible to search for resources using tags filter (without resouce group api). will share my idea or implementation if I have findings.

**Comment by tsupertramp** [comment]
Yeah bascially you list all resources and then filter them based on resources.

Initially yace was written without usage of tagging api. So every resource got there own service discovery. I migrated away from this after finding out about tagging api. So from my point of view it should be possible pretty easily.

There are generally two categories of aws services.
- e.g. ECS - Use describe clusters api call and get resources + tags https://docs.aws.amazon.com/sdk-for-go/api/service/ecs/#ECS.DescribeClusters
- e.g. Elasticache - Use describe Clusters  https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#DescribeCacheClustersOutput but afterwards get tags additionally through a second api call.

AWS Api is pretty inconsistent. So sometimes you get tags with resources and sometimes not and you need a second api call.

If you want I'll check out ecs metrics support tomorrow. Would be cool to have a first example of a non-tag-api example in the code.

**Comment by wutianchen** [comment]
@tsupertramp  thanks for the advice for the implementation. For me current the difficulty is the software architecture how to include both resource-group-api resources and non-resource-group-api resources together. API calls will be easy.

* At the moment ECS and iot supports tagging. Basically if non-tag-api resource is introduced into yace, it will not support the "searchTags" feature in config.yml. Is that right ?

**Comment by tsupertramp** [comment]
Sounds good. Thanks :) Just try something out and we discuss your approach afterwards?

**Comment by thomaspeitz** [comment]
Closing this. Feel free to PR if you want to add something :)
