### ISSUE TITLE
Configuration to get Amazon MQ metrics using YACE

### ISSUE THREAD

**Issue by Alexander-ac** [ivx/yet-another-cloudwatch-exporter#282]
Hi, I am trying to get amazon mq metrics using the YACE exporter. Does it support amazon mq metrics? If yes, can someone please help me with the configuration to get them?

**Comment by thomaspeitz** [comment]
Sorry we are not supporting this currently but it is supported by the resourcegroupstagging api

https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/Welcome.html

So it can be implemented. You are interested to PR?

**Comment by Alexander-ac** [comment]
Hello Thomas, thank you for your answer. Yes, am interested to PR. Can you give some examples?
Thank you in advance.

**Comment by retraut** [comment]
Any news here, guys? 
@Alexander-ac @thomaspeitz

**Comment by saez0pub** [comment]
I submitted the PR #358 for adding theses metrics :) . hope it helps
