### ISSUE TITLE
When i run the yet-another-cloudwatch-exporter，The following error occurred

### ISSUE THREAD

**Issue by wangfan0524** [ivx/yet-another-cloudwatch-exporter#303]
**Couldn't describe resources for region us-east-2: InvalidSignatureException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.**

But when I run the cloudwatch-exporter with the same authentication information, there are no errors，and ican get the data.

So，who can help me?thank you !

**Comment by thomaspeitz** [comment]
Please install aws cli on the host you are using and verify if credentials work it. Feel free to reopen if this is the problem.

Thanks Andrew for help here!
