### ISSUE TITLE
Add container security scanning + badge

### ISSUE THREAD

**Issue by thobach** [ivx/yet-another-cloudwatch-exporter#305]
Hi,

In order to keep the docker images up to date and secure, could the maintainers please add this repository to a service like Snyk that monitors and alerts when there are vulnerabilities or insecure configurations in the container image? Ideally a badge could be added to the README for quick visibility of the status.

Thanks!

**Comment by thomaspeitz** [comment]
Duplicate

**Comment by thobach** [comment]
Please see also my comment on https://github.com/ivx/yet-another-cloudwatch-exporter/issues/306#issuecomment-792291847
