### ISSUE TITLE
Add application dependency scanning + badge

### ISSUE THREAD

**Issue by thobach** [ivx/yet-another-cloudwatch-exporter#306]
Hi,

In order to keep the dependencies of this application up to date, could the maintainers please add this repository to a service like Snyk that monitors and alerts when there are vulnerabilities in the dependencies (https://github.com/ivx/yet-another-cloudwatch-exporter/blob/master/go.mod)? Ideally a badge could be added to the README for quick visibility of the status.

Thanks!

**Comment by thomaspeitz** [comment]
Duplicate

**Comment by thobach** [comment]
Hi, Is there a dependency vulnerability scanner embedded in the build and release process? https://support.snyk.io/hc/en-us/articles/360004032117-GitHub-integration describes some details how it could be accomplished using Snyk. Thanks!
Example:

- docker image scan (which currently contains a medium vulnerability, not disclosing details here): <img width="1246" alt="Bildschirmfoto 2021-03-07 um 15 53 26" src="https://user-images.githubusercontent.com/274056/110244061-43bbcf80-7f5d-11eb-9624-4d8b51ca37bb.png">
- application dependency scan (no vulnerabilities): <img width="1439" alt="Bildschirmfoto 2021-03-07 um 15 52 19" src="https://user-images.githubusercontent.com/274056/110244018-1bcc6c00-7f5d-11eb-9187-905deb1401f0.png">
