### ISSUE TITLE
Feature Request: Add type emr

### ISSUE THREAD

**Issue by wutianchen** [ivx/yet-another-cloudwatch-exporter#31]
Dear yace team,

we are trying to extend yace with additional type "emr". But seemingly emr has no resource arn, is that the reason why you haven't included it as a type ? 

Is it possible to implement type emr elegantly based on yace ?

Thanks a lot for the help

**Comment by tsupertramp** [comment]
As it is based on aws tagging api, this should be possible. https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/Welcome.html
This api should give you the ARN of the resource.

Namespace can be found here:
https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#genref-arns
Its elasticmapreduce

Do you want to try implementing it yourself with these hints?

Greetings, Thomas

**Comment by wutianchen** [comment]
Hi tsupertramp, thanks for the hints. I have implemented myself for elasticmapreduce, dynamodb, kinesis, firehose etc :) 

only one confusion what is the usage of hotfix in aws_tags.go

**Comment by tsupertramp** [comment]
That rocks - Thanks @wutianchen - Feel free to PR them in one big PR. Not needed one for every service.

If you need help with PR just tell me :)

**Comment by wutianchen** [comment]
Hi @tsupertramp sorry for the delayed response. I was in vocation. I have extended yace with minimal two types ecs_cluster and ecs_service. (ecs resources are extracted from go sdk, not resourcegroupapi). Due to some reason I can not PR the code, can we talk shortly about the idea ? please feel free to email me tcwooo@yahoo.com thanks a lot

**Comment by tsupertramp** [comment]
We can do it together. I am coming back to you in the following days. @wutianchen - Feel free to remove your email i saved it aleady.

**Comment by wutianchen** [comment]
@tsupertramp sure. will be available :)

**Comment by tsupertramp** [comment]
@wutianchen - Email is out. Totally forgot this topic.

**Comment by prakharjoshi** [comment]
@tsupertramp any plans to merge the CW metrics for DynamoDB? Is any work going on for the same? Or we can add DynamoDB service too?

**Comment by tsupertramp** [comment]
Currently it seems not @prakharjoshi - Would love to review a dynamodb PR :)

**Comment by tsupertramp** [comment]
@prakharjoshi - Just implemented dynamodb as i was preparing the release anyways.

**Comment by wutianchen** [comment]
@tsupertramp  Hi sorry for the delayed response. I am off from the topic for a while. new feature release from resource grouping api https://aws.amazon.com/about-aws/whats-new/2019/02/resource-groups-tagging-api-supports-additional-aws-services/. I can imagine dynamodb is coming in the near future :)

**Comment by wutianchen** [comment]
@tsupertramp  at the moment it seems to be hard to structure different combinations of dimensions for one service. for example, ecs:cluster and ecs:service

**Comment by tsupertramp** [comment]
Dynamodb is implemented @wutianchen and released :)

Yeah dimensions are very hard. The AWS api is different all the time :/

I hope EMR is coming soon.

**Comment by thomaspeitz** [comment]
EMR was added.
