### ISSUE TITLE
EC2 metrics intermittent 

### ISSUE THREAD

**Issue by arnitolog** [ivx/yet-another-cloudwatch-exporter#32]
for some reason EC2 metrics are intermittent:
![image](https://user-images.githubusercontent.com/34036079/49525512-99086280-f8b6-11e8-9c9c-e22d927c452d.png)
at the same time metrics for RDS behave as expected:
![image](https://user-images.githubusercontent.com/34036079/49525955-88a4b780-f8b7-11e8-8ddf-ff80abfdd321.png)

here is the config for both resources:
      jobs:
      - region: {{ .Values.exporter.region }}
        type: "rds"
        searchTags:
          - Key: Product
            Value: .*
        metrics:
          - name: CPUUtilization
            statistics:
            - 'Average'
            period: 60
            length: 300
          - name: FreeStorageSpace
            statistics:
            - 'Minimum'
            period: 60
            length: 300
          - name: DatabaseConnections
            statistics:
            - 'Maximum'
            period: 60
            length: 300

      - region: {{ .Values.exporter.region }}
        type: "ec2"
        searchTags:
          - Key: Product
            Value: .*
        metrics:
          - name: CPUUtilization
            statistics:
            - 'Average'
            period: 60
            length: 300
          - name: NetworkIn
            statistics:
            - 'Average'
            period: 60
            length: 300
          - name: NetworkOut
            statistics:
            - 'Average'
            period: 60
            length: 300

And I use 0.10.0 version of the exporter. Could you please advise where I'm wrong

**Comment by tsupertramp** [comment]
Will look into this on Friday.

**Comment by arnitolog** [comment]
Thank you.
one more observation:
if EC2 job goes first and then RDS we will see the picture above.
But if we swap these jobs, without any other config changes, EC2 metrics completely disappear.

**Comment by tsupertramp** [comment]
Out of healthy reasons i had to skip this today. - I will try to do it end of next week. - But i can verify this happens to us as well. My feeling is that aws returms sometimes nill.

**Comment by arnitolog** [comment]
Hi @tsupertramp , have you had a chance to look at this issue?

**Comment by arnitolog** [comment]
I will try different parameters. Unfortunately, I'm not sure about tomorrow, but anyway will post all collected data.

**Comment by arnitolog** [comment]
what I found so far is that any combination of values less than below causes an issue:
            period: 60
            length: 600
This is only for EC2, for RDS 60/300 works well.

**Comment by tsupertramp** [comment]
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-cloudwatch-new.html

ec2 basic monitoring - "Data is available automatically in 5-minute periods at no charge."

https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_concepts.html

So you need at least a period of 300. If you scrape every 10m i would set length to 600. If you check every 5min use length 300.

As soon as i am healthy again i will add some code to validate on start.

**Comment by tsupertramp** [comment]
Mhm interesting. Will try out for ourselves as well. Lets see which results we get. I'll keep this open till docs / code is adjusted and ux is better.

**Comment by tsupertramp** [comment]
Added some troubleshooting in README.md

Closing this here.
