### ISSUE TITLE
permission denied for /tmp/config.yml

### ISSUE THREAD

**Issue by akhilr134** [ivx/yet-another-cloudwatch-exporter#330]
Hello There, 

I got into a weird issue. While running the below command.

`docker run -d --rm -v $PWD/credentials:/exporter/.aws/credentials -v $PWD/config.yml:/tmp/config.yml  -p 5000:5000 --name yace quay.io/invisionag/yet-another-cloudwatch-exporter:v0.25.0-alpha -debug -config.file /tmp/config.yml`

`Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Trying to pull quay.io/invisionag/yet-another-cloudwatch-exporter:v0.25.0-alpha...
Getting image source signatures
Copying blob 1d7f164cde91 done  
Copying blob 1e044a4e9ff2 done  
Copying blob d10629ff8eaa done  
Copying blob 801bfaa63ef2 done  
Copying config e379306e35 done  
Writing manifest to image destination
Storing signatures
13cb194fade9830ec2e3774be96af15a58dc3c644295331b820967ffcd1fb235`

While running the docker 

`docker run e379306e3598
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
{"level":"info","msg":"Parse config..","time":"2021-03-08T12:01:17Z"}
{"level":"fatal","msg":"Couldn't read /tmp/config.yml: open /tmp/config.yml: no such file or directory","time":"2021-03-08T12:01:17Z"}`

But I already have a file named config.yml in /tmp

`ll /tmp/config.yml 
-rw-r--r--. 1 root root 210 Mar  8 12:55 /tmp/config.yml`

The other error I'm facing is

`docker run -ti -p 5000:5000 -v /home/ec2-user/git/yet-another-cloudwatch-exporter/credentials:/exporter/.aws/credentials -v /home/ec2-user/git/yet-another-cloudwatch-exporter/yace-config.yml:/tmp/config.yml e379306e3598
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
{"level":"info","msg":"Parse config..","time":"2021-03-08T11:57:07Z"}
{"level":"fatal","msg":"Couldn't read /tmp/config.yml: open /tmp/config.yml: permission denied","time":"2021-03-08T11:57:07Z"}`

Please help me resolving this issue. Thanks

**Comment by akhilr134** [comment]
My bad, wrong config path, working fine

**Comment by ravirai2020** [comment]
I am trying to run ECS task with YACE image. I also get same error. I am mounting EFS share which has config.yaml file with permission 777. I tried to change path to /mnt too but same permission denied error. Could you please let me know what path should be used to mount?

**Comment by ravirai2020** [comment]
> My bad, wrong config path, working fine
@akhilrepo  I am trying to run ECS task with YACE image. I also get same error. I am mounting EFS share which has config.yaml file with permission 777. I tried to change path to /mnt too but same permission denied error. Could you please let me know what path should be used to mount?
