### ISSUE TITLE
Support for changing tag_ prefix

### ISSUE THREAD

**Issue by sanchezpaco** [ivx/yet-another-cloudwatch-exporter#34]
Hi!

We need in our integration of the exporter, tags exported without the prefix `tag_`.

What do you think of supporting an env variable, a parameter inside the config.yml or something similar for changing the prefix to whatever you want?

**Comment by tsupertramp** [comment]
Hey, not against it but would like to understand the underlying problem a little bit more.

**Comment by sanchezpaco** [comment]
It's just a case that we have, we are using gitlab and by default it uses a query like {environment: "xxxx"}. We have the environment tag and the exporter it's exporting it like `tag_environment` (as expected).

We have forked the repository and changed it for making it work without editing gitlab config, so my question was if it was nice to have a configuration to override the `tag_` prefix

**Comment by tsupertramp** [comment]
Hey @sanchezpaco - You should be able to relabel on prometheus - https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config - So from my perspective we should not implement it. Or did i misunderstood you?

**Comment by sanchezpaco** [comment]
Oh I see, I didn't know prometheus had this configuration, maybe this would work! Thanks :)
