### ISSUE TITLE
Transit Gateway Attachments

### ISSUE THREAD

**Issue by rhys-evans** [ivx/yet-another-cloudwatch-exporter#372]
Hi 

I am looking to upgrade to one of the latest versions of yace, however I see the `tgwa` (transit gateway attachment) metric has been removed in https://github.com/ivx/yet-another-cloudwatch-exporter/pull/315. 

Just looking to see if there was a particular reason etc for this ?

Thanks

**Comment by rhysxevans** [comment]
Sorry, just looked a the code it seems to have been merged under TGW. thanks
