### ISSUE TITLE
Set timestamps for the exported metrics

### ISSUE THREAD

**Issue by bandesz** [ivx/yet-another-cloudwatch-exporter#38]
We plan to add support to expose the exact timestamps for the exported metrics.

For this to work we will:
 - upgrade the go client library to at least 0.9.0 (they added support for timestamped metrics)
 - add a configuration option to set the timestamps (defaults to true)

Is this something you would be happy with?
Should we open separate PRs to upgrade the go client and add the timestamp feature?
Do we need the config option or would it be fine to always expose the timestamps?

**Comment by tsupertramp** [comment]
@bandesz Hey, that sounds awesome. Thanks! I am fine with one PR. Timestamps were introduced with 2.x.x which is more than a year ago. So i would not make it configurable. I will add some hint in the CHANGELOG on release. Would you add the minimum specs to the README please?

Greetings, Thomas

Greetings, Thomas

**Comment by LeePorte** [comment]
PR has been opened https://github.com/ivx/yet-another-cloudwatch-exporter/pull/39

**Comment by tsupertramp** [comment]
I am closing this issue.

Merged and released as 0.12.0-alpha. Will test the next days if there are unexpected problems and then release as stable.

Thanks a lot for your work!
