### ISSUE TITLE
Does YACE support Azure Monitoring?

### ISSUE THREAD

**Issue by anoop2503** [ivx/yet-another-cloudwatch-exporter#397]
Is YACE supporting to collect metrics from Azure Monitor?

**Comment by aobertyshev** [comment]
You can use the following exporters for Azure Monitor:
https://github.com/RobustPerception/azure_metrics_exporter
https://github.com/webdevops/azure-metrics-exporter (I use this one)

**Comment by anoop2503** [comment]
Thank you @aobertyshev

**Comment by thomaspeitz** [comment]
This is currently not intended.
