### ISSUE TITLE
incorrect dimension value in case of alb in discovery config

### ISSUE THREAD

**Issue by GeeksWine** [ivx/yet-another-cloudwatch-exporter#42]
Hi,
in discovery config, when `alb` instances are searched based on tags and dimensions are made from these searched values, dimension value which passed in this case is a bit incorrect. After making the changes, this works for me and have created pull request for the same: https://github.com/ivx/yet-another-cloudwatch-exporter/pull/41
Please let me know regarding this.

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-cloudwatch-metrics.html#load-balancer-metric-dimensions-alb
here it specifies: in case of 'LoadBalancer' dimension, its value should be 'app/load-balancer-name/1234567890123456'

**Comment by tsupertramp** [comment]
Thanks @GeeksWine for your find and PR :)

I will try to look through it this evening.

**Comment by GeeksWine** [comment]
Sure :)

**Comment by tsupertramp** [comment]
Reviewed looks good for me.

Let me get some feedback from the intial commiter of the ALB support and then we will merge it.

Greetings, Thomas

**Comment by tsupertramp** [comment]
After your PR i still got - ```loadbalancer/app/test-alb/d8891039351671d7``` but it should be ```app/test-alb/d8891039351671d7``` 

Here it needs to be trimmed as well: 

https://github.com/ivx/yet-another-cloudwatch-exporter/commit/963942f6aa98d93c49a9b5e0a7b05fa9fbac2e44

Fixed this. Any case where this breaks your alb usage? @GeeksWine

**Comment by GeeksWine** [comment]
Hi @tsupertramp , please the comment here.
https://github.com/ivx/yet-another-cloudwatch-exporter/pull/52

**Comment by tsupertramp** [comment]
Released in 0.13.0-alpha - Thanks for your work!
