### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by lswith** [ivx/yet-another-cloudwatch-exporter#5]
This looks epic!

Could we get a helm chart to make installation easy?

**Comment by tsupertramp** [comment]
Why not :) - Will do it. Sorry not sure why i overslept this notification

**Comment by tsupertramp** [comment]
No helm chart planned currently. Feel free to PR one, i will review and merge.

**Comment by glaracuente** [comment]
haven't tried it yet, but this looks promising: https://hub.kubeapps.com/charts/mogaal/prometheus-yace-exporter
