### ISSUE TITLE
Throttling: Rate exceeded 

### ISSUE THREAD

**Issue by arnitolog** [ivx/yet-another-cloudwatch-exporter#50]
Hello, 

faced with panic in one of the regions:
`panic: Throttling: Rate exceeded
        status code: 400, request id: 2eac2d08-4014-11e9-8a89-991f83fb4554

goroutine 8238 [running]:
main.cloudwatchInterface.get(0xa3d040, 0xc420276018, 0xc4215abe80, 0xc422c00c60, 0xc42009f150, 0xe)
        /go/src/yace/aws_cloudwatch.go:112 +0x17d
main.scrapeDiscoveryJob.func1.1(0xc42025d680, 0xc420d00410, 0xc4259bba00, 0x2, 0x2, 0xc422c3d6d0, 0x1, 0x1, 0xa3d040, 0xc420276018, ...)
        /go/src/yace/abstract.go:140 +0x1dd
created by main.scrapeDiscoveryJob.func1
        /go/src/yace/abstract.go:123 +0x15d`

Probably it makes sense to handle this via some configuration option. Like: "max concurrent requests" or something.

**Comment by Hashfyre** [comment]
We are also seeing similar issues:
```
2019/03/07 11:12:14 Parse config..
2019/03/07 11:12:14 Startup completed
panic: Throttling: Rate exceeded
	status code: 400, request id: 5b295e7c-40ca-11e9-a04e-01c609075034

goroutine 230493 [running]:
main.cloudwatchInterface.get(0xa1f9c0, 0xc4201f6330, 0xc42023ea80, 0xc4204322b0, 0xc4200294b0, 0xe)
	/go/src/yace/aws_cloudwatch.go:110 +0x17d
main.scrapeDiscoveryJob.func1.1(0xc42547f5f0, 0xc421411a90, 0xc87838, 0x0, 0x0, 0xc4201f6168, 0x1, 0x1, 0xa1f9c0, 0xc4201f6330, ...)
	/go/src/yace/abstract.go:138 +0x1b3
created by main.scrapeDiscoveryJob.func1
	/go/src/yace/abstract.go:122 +0x15d
```

**Comment by tsupertramp** [comment]
Will work on this in the next version.

Could you both tell me how much resources are you monitoring with yace, just to get a feeling.

In which interval are you scraping?

**Comment by arnitolog** [comment]
here is my current configuration:
 `    - region: us-east-1
        type: "ec2"
        searchTags:
          - Key: Product
            Value: .*
        metrics:
          - name: CPUUtilization
            statistics:
            - 'Average'
            period: 60
            length: 600
            disableTimestamp: true
          - name: NetworkIn
            statistics:
            - 'Average'
            period: 60
            length: 600
            disableTimestamp: true
          - name: NetworkOut
            statistics:
            - 'Average'
            period: 60
            length: 600
            disableTimestamp: true
      - region: `us-east-1`
        type: "rds"
        searchTags:
          - Key: Product
            Value: .*
        metrics:
          - name: CPUUtilization
            statistics:
            - 'Average'
            period: 60
            length: 300
            disableTimestamp: true
          - name: FreeStorageSpace
            statistics:
            - 'Minimum'
            period: 60
            length: 300
            disableTimestamp: true
          - name: DatabaseConnections
            statistics:
            - 'Maximum'
            period: 60
            length: 300
            disableTimestamp: true
          - name: FreeableMemory
            statistics:
            - 'Average'
            period: 60
            length: 300
            disableTimestamp: true`

we are using spot instances for jenkins agents which also monitored with yace exporter. And I guess the number of agents is causing an issue. Here is a count of some of the metric from yace:
![image](https://user-images.githubusercontent.com/34036079/54072443-8ae62b80-4283-11e9-890e-26dfdc42944c.png)

And current limits from AWS is: 
GetMetricStatistics - 400 transactions per second (TPS)

**Comment by tsupertramp** [comment]
How is your prometheus instance configured? - Scraping interval. Every 15 seconds you are getting metrics from yace?

**Comment by arnitolog** [comment]
No, we are getting metrics every 60sec:
        scrape_interval: 60s
        scrape_timeout: 60s

**Comment by tsupertramp** [comment]
Could you check how many api calls you are creating per minute:
```delta(yace_cloudwatch_requests_total[1m])```

 @arnitolog

**Comment by arnitolog** [comment]
@tsupertramp it will show nothing due to my scrape interval is equal 1m.
But here are values for 2 and 5 minutes:
delta(yace_cloudwatch_requests_total{aws_cluster="us-east-1-cicd",job="yace_cloudwatch"}[2m]) 4890
delta(yace_cloudwatch_requests_total{aws_cluster="us-east-1-cicd",job="yace_cloudwatch"}[5m]) 12247

**Comment by arnitolog** [comment]
also, here is a graph for the same metric for the last 7 days:
![image](https://user-images.githubusercontent.com/34036079/54125054-a2045500-440c-11e9-8be1-9e33b30d7b60.png)

**Comment by tsupertramp** [comment]
Thanks for all the data!

Okay, i will think how we can solve this. We need to reduce the api calls to fix this. Not sure maybe through grouping more api calls into one.

Will take some time but challenge accepted to solve this.

And great to have someone using it in such a big setup! :)

**Comment by wutianchen** [comment]
@tsupertramp @arnitolog  encountered the same problem. solved with limiting the number of go routines

**Comment by tsupertramp** [comment]
Thanks for the idea @wutianchen - Will add this on Friday.

Any tipps how you set them?

**Comment by wutianchen** [comment]
@tsupertramp  I used an extra parameter called maxConcurrency to limit the number of goroutines. Here is the notes I used in my implementation https://gitlab.com/wutianchen/ds-codebase/blob/master/Golang/patterns.md . If you need me we can also talk shortly on Friday :) best

**Comment by tsupertramp** [comment]
Will need to skip this to weekend. Already spent two hours on alb research..

**Comment by wutianchen** [comment]
Hi @tsupertramp , do you have this implemented, we are preparing our contribution to the open source.

**Comment by tsupertramp** [comment]
No did not @wutianchen - Would be happy to merge it :)

**Comment by tsupertramp** [comment]
@wutianchen - Should i add this now? - Currently doing contributions and could add this. As this should fix a lot of users problems.

**Comment by wutianchen** [comment]
@tsupertramp  afraid the political things about open source contribution could take several weeks... pls feel free to add this. I am working on custom metrics and haven't come to a good solution. might be able to contribute this part in the future. hopefully

**Comment by wutianchen** [comment]
@tsupertramp I am catching up your updates. already several versions behind.  wait for our internal "Open Source Contribution" policy :) and then PR

**Comment by tsupertramp** [comment]
I am implementing this one on Friday so we get a fix in place.

If you have a better solution lets switch them as soon as you are ready @wutianchen - I really appreciate all the work you do to get your commits into the public version :)

Greetings, Thomas

**Comment by tsupertramp** [comment]
@arnitolog @Hashfyre - Just released 0.13.5-alpha with a possible fix for rate limit exceeded. Would you be so kind and test it? - It limits concurrency of aws requests to 5. If this is too high or too low i would like to change it. Would avoid making it configurable and better set some nice values which fits for the whole community. The target of the project is to make it as easy as possible to monitor aws with prometheus.

**Comment by arnitolog** [comment]
Thanks a lot, @thomaspeitz. Unfortunately, I don't have such a big env now. Previously we had hundreds of Jenkins Agents. And getting metric for them caused this issue. Now we moved Jenkins into Kubernetes along with its agents. So I don't have a good test field for experiment. But I definitely will install the latest version across all my environments

**Comment by thomaspeitz** [comment]
Closing - In case of any other user get this problem please tag me here. I will reopen. Thanks

**Comment by arnitolog** [comment]
@thomaspeitz, just added ALB/ELB metrics to YACE 0.13.6 and got the same error:
panic: Throttling: Rate exceeded
        status code: 400, request id: 4c6aa090-9ce9-11e9-9bc2-75915715ef13

goroutine 9025 [running]:

**Comment by arnitolog** [comment]
@thomaspeitz seems like I found the issue. please check https://github.com/ivx/yet-another-cloudwatch-exporter/pull/77

**Comment by arnitolog** [comment]
it is still failing. need to take a closer look.

**Comment by arnitolog** [comment]
in my configuration, I have 2 Prometheus servers which scrape the same set of targets. So, probably this causes an issue with yace and Throttling. 2 servers scrape the same yace exporter which triggers a lot of simultaneous api requests.

**Comment by thomaspeitz** [comment]
Closing again.
