### ISSUE TITLE
Turn off timestamp as default to remove ux bug

### ISSUE THREAD

**Issue by karlesnine** [ivx/yet-another-cloudwatch-exporter#51]
With yace version 0.12 and prometheus 2.7.2 I got a scrape error **expected timestamp or new record, got "MNAME"**. Yace run without message or warning, everything is ok but prometheus fail to scrape and note the target down

With yace version 0.11 and prometheus 2.7.2 everything is ok

Not thing change in our yace-config.yml between yace version 0.11 and  yace version 0.12

Note, promtool check metrics report some metric name warning
> curl http://172.31.68.219:5000/metrics | /opt/prometheus/prometheus-2.7.2.linux-amd64/promtool check metrics
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  3261  100  3261    0     0  74113      0 --:--:-- --:--:-- --:--:-- 74113
> aws_elb_backend_connection_errors_sum non-histogram and non-summary metrics should not have "_sum" suffix
> aws_elb_httpcode_backend_2_xx_sum non-histogram and non-summary metrics should not have "_sum" suffix
> aws_elb_httpcode_backend_4_xx_sum non-histogram and non-summary metrics should not have "_sum" suffix
> aws_elb_httpcode_backend_5_xx_sum non-histogram and non-summary metrics should not have "_sum" suffix
> aws_elb_request_count_sum non-histogram and non-summary metrics should not have "_sum" suffix

**Comment by tsupertramp** [comment]
@karlesnine - Could you try to disable timestamps and or try to set period length at least to 600 (5m) - Just to test if this works.

 https://github.com/ivx/yet-another-cloudwatch-exporter#metric-definition

**Comment by karlesnine** [comment]
The period was already to 60 (1m)
I was disable timestamps for all metric (vpn, elb,rds,ec,lambda). We not monitor S3 yet 
... and everything work great

I thought disableTimestamp was not mandatory and was only useful for a use case with S3. I find it strange to have a mandatory parameter to disable a feature

**Comment by tsupertramp** [comment]
Me as well.

Will turn it off as default in next version. I think this is from ux perspective a lot better.

Sorry for the annoyance.

**Comment by tsupertramp** [comment]
Released in 0.13.0-alpha

**Comment by Hashfyre** [comment]
We have started getting this error after upgrading to `v0.13.1-alpha`
```
level=warn ts=2019-04-15T07:41:07.833982293Z caller=scrape.go:836 component="scrape manager" scrape_pool=monitoring/cloudwatch-exporter/0 target=http://p.q.r.s:5000/metrics msg="append failed" err="expected timestamp or new record, got \"MNAME\""
```

**Comment by Hashfyre** [comment]
@tsupertramp can this be looked into again? Let me know if I can provide you with additonal data to validate the issue.

**Comment by tsupertramp** [comment]
Closing this @Hashfyre - Feel free to tag me and i will reopen. 

Would like to know if you disabled timestamp and it is still happening.
