### ISSUE TITLE
Add Dimensions as Labels

### ISSUE THREAD

**Issue by adamdougal** [ivx/yet-another-cloudwatch-exporter#53]
Hey, I’m looking at switching from [cloudwatch_exporter](https://github.com/prometheus/cloudwatch_exporter) to yace to be able to get tags into our metrics (thanks btw!). I’m just comparing the differences between them and one potential issue is that yace doesn’t add dimensions as labels like `cloudwatch_exporter`. 

## Labels for EC2 CPUCreditBalance:
**cloudwatch_exporter**
```
{job="aws_ec2",instance="",instance_id=“some-instance-id“,}
```

**yace**
```
{name="arn:aws:ec2:eu-west-1:some-owner:instance/some-instance-id”, tag_Foo=“bar”}
```

## Labels for ES CPUUtilization
**cloudwatch_exporter**
```
{job="aws_es",instance="",domain_name=“some-domain-name”,client_id="some-client-id",}
```

**yace**
```
{name="arn:aws:es:eu-west-1:some-client-id:domain/some-domain-name", tag_Foo=“bar”}
```

The data is there in the `name` label but unless you know how to break it down it’s not clear.

Is this something you’d be happy adding? I'm also happy to raise a PR? Could prefix the labels with `dimension_` similar to `tag_`?

**Comment by tsupertramp** [comment]
Sounds awesome @adamdougal 

I would be very happy about a PR. No need to make it optional. I would suggest adding it to all metrics as default.
