### ISSUE TITLE
Add availabilicy zone for ec2 instances metrics

### ISSUE THREAD

**Issue by LuciferInLove** [ivx/yet-another-cloudwatch-exporter#58]
Hello. Is it possible to add availability zone as label for ec2 instances metrics?

**Comment by tsupertramp** [comment]
Hey @LuciferInLove you can tag them with availability zone then you could attach the tags to the metrics.

Adding the availability zone would mean that we need to add informations by another api which is currently not planned.

Does this help you?

**Comment by LuciferInLove** [comment]
Thank you for answer. I'm already using tags) Sorry for worrying, if it's not planned. Or you can just keep this issue as feature request.

**Comment by tsupertramp** [comment]
Closing this but added some summarized issue for that feature request. This would change the handling of the exporter.

I am not 100% sure how and if this should be integraded. But i will keep it in mind.
