### ISSUE TITLE
Gap in the prometheus time series

### ISSUE THREAD

**Issue by wutianchen** [ivx/yet-another-cloudwatch-exporter#62]
as already being pointed out in the documentation https://github.com/ivx/yet-another-cloudwatch-exporter#help-my-metrics-are-intermittent.

The length could cause a problem of intermittent metrics.

My thinking is the following:

Why would I consider a length of 600, when I can set it 1800. because in the case of 1800 yace scraper looks back 1800s(=30m) and take the latest data point (as far as I have understood). 

Isn't always better than length: 600 ? (which only looks back 10m, and deliver missing value if nothing found, most likely due to the lagging of cloudwatch api).

The only drawback I can think of is, yace or prometheus has to process 3 times the amount of data. But that is nothing in most of the case.

**Comment by tsupertramp** [comment]
Added warning on boot
