### ISSUE TITLE
Feature request: Add task role as credential provider for secure ecs usage

### ISSUE THREAD

**Issue by MattFre** [ivx/yet-another-cloudwatch-exporter#64]
Hello,

the YACE plugin runs in a docker container in an AWS ECS. The Container can get credentials by using the instance profile. For security reasons the Container should not use the instance Profile. Instead it should use a task role, that is attached to the ECS task. But this configuration results in following error:

Couldn't describe resources: NoCredentialProviders: no valid providers in chain. Deprecated.
For verbose messaging see aws.Config.CredentialsChainVerboseErrors

It seems the task role is not checked as a credential provider. 

Coud you add the task role as a possible credential provider?

Best regards
Matthias

**Comment by tsupertramp** [comment]
Hey Matthias,

i am not familiar with ecs but i will check this in the following weeks. Need to start an ecs cluster and validate why it is not working.

Greetings, Thomas

**Comment by tsupertramp** [comment]
Will fix this as soon as v2 is out - V2 fixes this automatically through new credential provider - Researched a bit but could not quick fix this in a time frame of 15 minutes. https://github.com/aws/aws-sdk-go-v2

So this will be laying around for a while.

I am open to review PRs if anyone wants to add it.

Sorry @MattFre

**Comment by thomaspeitz** [comment]
Still v2 not out. But i have it still on my list.

**Comment by lbenedetto** [comment]
Any updates on this issue?

**Comment by lbenedetto** [comment]
I've create a pull request to upgrade to the v2 sdk
https://github.com/ivx/yet-another-cloudwatch-exporter/pull/149

**Comment by lbenedetto** [comment]
I was actually able to get IRSA working with yace without any changes. Just had to fix an issue with the helm chart using the default service account instead of the one I specified.

I'll leave the pull request open in case you want anything from it, but I will not be working on it any further.

**Comment by SerhiiSokolov** [comment]
@lbenedetto 
Can you put here a bit description of how did you get IRSA working?
I've added 
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::***
to a service account that is used by pod, but still get
2020/05/05 12:14:45 Couldn't describe resources:  AccessDeniedException: User: arn:aws:sts::**********:assumed-role/*********/i-0ce5c5******** is not authorized to perform: tag:GetResources
because YACE uses instance profile not the role attached to service account.

**Comment by lbenedetto** [comment]
Here are the changes I made to the helm chart to fix the issue.
https://github.com/mogaal/helm-charts/pull/2/files

**Comment by thomaspeitz** [comment]
Still a problem @SerhiiSokolov ?
