### ISSUE TITLE
Feature request: Support for aws custom metrics

### ISSUE THREAD

**Issue by wutianchen** [ivx/yet-another-cloudwatch-exporter#65]
we want to export custom metrics in cloudwatch into prometheus through yace.

Because custom metrics have 

1. undetermined value of dimension which doesn't come from resource arn, so it can not be exported through "discovery" block.
2. it has too many options for value, so it is hard to register into "static" block manually.

so we need some new mechanism to export custom metrics in yace, as far as I have understood.

**Comment by wutianchen** [comment]
@tsupertramp  would a feature like reading static configure from dynamodb table instead of config.yml make sense ?

**Comment by tsupertramp** [comment]
Which value do you want @wutianchen ?

**Comment by wutianchen** [comment]
hmm.. basically any possible metrics published by the user https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/publishingMetrics.html

**Comment by tsupertramp** [comment]
Ah did not get it what you meant with custom metrics.

Could you describe what you are doing with it. So i can understand the whole use case better. I know we did memory of windows instances in the past. But we no more need it ourselves.

Would be interested in your use case.

**Comment by wutianchen** [comment]
custom metrics mean it could be not metrics from AWS services. simply some values with timestamp written by some one into cloudwatch.

For example, some one write SUCCESS(1) / FAIL (0) into cloudwatch 

namespace: "MySQL"
metric: "queryCheck"
Dimension: queryName

and those metrics need to be available in prometheus, you can not get it throug normal "discovery" and "static"

**Comment by tsupertramp** [comment]
I am currently not implementing this as we do not have this need for it. But i would happy to review a PR. In the meantime i let it open as feature Request for other people +1 (please as emoji!)

**Comment by wutianchen** [comment]
@tsupertramp  already implemented, now I can add custom metrics with a extra block in the config file like

custom:
  - namespace: ECS
    region: eu-central-1
    metrics:
      - name: number_of_task_starts
        statistics:
        - 'Sum'
        period: 600
        length: 1200

P.S. the "open source contribution" request within our organization goes well, it might take ONLY another few weeks until I can make a PR for this :) ...

**Comment by sujithpaily** [comment]
Is this feature included in latest version v0.13.6 ?
I have tried the following config but not worked

custom:
  - namespace: CWAgent
    region: us-east-1
    metrics:
      - name: mem_used_percent
        statistics:
             - Average
        period: 300
        length: 600

I am using cloudwatch exporter to monitor memory and disk usage. In prometheus cloudwatch exporter its working

**Comment by thomaspeitz** [comment]
Custom metrics are not added yet. @sujithpaily - Sorry!

**Comment by marpada** [comment]
I'm confused with this request. What is the difference between a static and custom? I just add my custom metrics to the static block.

**Comment by thomaspeitz** [comment]
Marpada is totally right - Thanks. Normally it should work. Can you try to get the data through AWS CLI and show me how you get it. Then i can help you to add it to yace @sujithpaily

**Comment by thomaspeitz** [comment]
Closed as it should be working. Tag me if not.
