### ISSUE TITLE
YACE manages to get metrics but crashes at the end

### ISSUE THREAD

**Issue by jonasv** [ivx/yet-another-cloudwatch-exporter#68]
Hi,

I've got weird crash error, please have a look and comment is this a bug or configuration problem:

./yet-another-cloudwatch-exporter -debug
2019/05/22 16:31:30 Parse config..
2019/05/22 16:31:30 Startup completed
2019/05/22 16:31:35 CLI helper - aws cloudwatch get-metric-statistics --metric-name SuccessfulCalls --dimensions  --namespace AWS/EC2/API --statistics Sum --period 60 --start-time 2019-05-22T16:26:35Z --end-time 2019-05-22T16:31:35Z
2019/05/22 16:31:35 {
  EndTime: 2019-05-22 16:31:35.95210587 +0000 UTC m=+5.863628358,
  MetricName: "SuccessfulCalls",
  Namespace: "AWS/EC2/API",
  Period: 60,
  StartTime: 2019-05-22 16:26:35.952108304 +0000 UTC m=-294.136369495,
  Statistics: ["Sum"]
}
2019/05/22 16:31:35 {
  EndTime: 2019-05-22 16:31:35.95210587 +0000 UTC m=+5.863628358,
  MetricName: "SuccessfulCalls",
  Namespace: "AWS/EC2/API",
  Period: 60,
  StartTime: 2019-05-22 16:26:35.952108304 +0000 UTC m=-294.136369495,
  Statistics: ["Sum"]
}
2019/05/22 16:31:36 {
  Datapoints: [
    {
      Sum: 227,
      Timestamp: 2019-05-22 16:30:00 +0000 UTC,
      Unit: "None"
    },
    {
      Sum: 146,
      Timestamp: 2019-05-22 16:26:00 +0000 UTC,
      Unit: "None"
    },
    {
      Sum: 128,
      Timestamp: 2019-05-22 16:27:00 +0000 UTC,
      Unit: "None"
    },
    {
      Sum: 173,
      Timestamp: 2019-05-22 16:28:00 +0000 UTC,
      Unit: "None"
    },
    {
      Sum: 201,
      Timestamp: 2019-05-22 16:29:00 +0000 UTC,
      Unit: "None"
    }
  ],
  Label: "SuccessfulCalls"
}
2019/05/22 16:31:36 http: panic serving 10.96.98.133:59700: descriptor Desc{fqName: "aws_ec2/api_successful_calls_sum", help: "Help is not implemented yet.", constLabels: {}, variableLabels: []} is invalid: "aws_ec2/api_successful_calls_sum" is not a valid metric name
goroutine 4 [running]:
net/http.(*conn).serve.func1(0xc0001dc140)
	/usr/lib/golang/src/net/http/server.go:1746 +0xd0
panic(0x95b9c0, 0xc00044f470)
	/usr/lib/golang/src/runtime/panic.go:513 +0x1b9
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc00036c0a0, 0xc0000dbcc0, 0x1, 0x1)
	/root/go/pkg/mod/github.com/prometheus/client_golang@v0.9.2/prometheus/registry.go:391 +0xad
main.metricsHandler(0xae4f80, 0xc000212000, 0xc0001d4400)
	/root/yet-another-cloudwatch-exporter/main.go:50 +0x2e1
net/http.HandlerFunc.ServeHTTP(0xa1a7b8, 0xae4f80, 0xc000212000, 0xc0001d4400)
	/usr/lib/golang/src/net/http/server.go:1964 +0x44
net/http.(*ServeMux).ServeHTTP(0xe895c0, 0xae4f80, 0xc000212000, 0xc0001d4400)
	/usr/lib/golang/src/net/http/server.go:2361 +0x127
net/http.serverHandler.ServeHTTP(0xc0001c8680, 0xae4f80, 0xc000212000, 0xc0001d4400)
	/usr/lib/golang/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc0001dc140, 0xae5800, 0xc000066700)
	/usr/lib/golang/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/lib/golang/src/net/http/server.go:2851 +0x2f5

As you can see I get datapoints, but unfortunately yace crashes without moving forward, please advice.

My config:

static:
  - namespace: 'AWS/EC2/API'
    region: redacted
    metrics:
      - name: SuccessfulCalls
        statistics:
        - 'Sum'
        period: 60
        length: 300

Thanks,
Jonas

**Comment by jonasv** [comment]
Hi,

I managed to find that if I fully remove this conditional here https://github.com/prometheus/client_golang/blob/master/prometheus/desc.go#L83 , remove model import and recompile yace - I can get get stats without crash, but I think it is not a wise choice as it was there on purpose.

**Comment by tsupertramp** [comment]
Currently on kubecon in barcelona. I will check it on Friday or the weekend when i am back. Thanks for the nice description. Will try to trigger this on my side.

**Comment by jonasv** [comment]
Hey,

thanks for reply. Was there any updates on this potential issue yet ?

**Comment by tsupertramp** [comment]
Ah i just learned about this opt in feature - https://docs.aws.amazon.com/AWSEC2/latest/APIReference/monitor.html

Will be fixed with next release today. Please test and give some feedback @jonasv :)

**Comment by tsupertramp** [comment]
@jonasv - Fix is out - Would you be so kind and test the latest version for me? - Thanks!

**Comment by jonasv** [comment]
Thanks for a fix! Will test this today.

**Comment by jonasv** [comment]
All good, thank you!

**Comment by tsupertramp** [comment]
Thanks for your quick feedback. Have fun using it!
