### ISSUE TITLE
Help: Docker config file location

### ISSUE THREAD

**Issue by sujithpaily** [ivx/yet-another-cloudwatch-exporter#71]
Hi

Im getting error 
Couldn't read config.yml:open config.yml: no such file or directory
Where should I mount/copy config.yml in docker

**Comment by thomaspeitz** [comment]
Hey @sujithpaily  /root/config.yml should be default.

**Comment by sujithpaily** [comment]
It worked. Thank you. Does yace support IAM user authetication by passing AWS_ACCESS_KEY_ID and SECRET_KEY as enviroment variables?

**Comment by thomaspeitz** [comment]
That should work - @sujithpaily  - Could you try out and give me feedback? - Then i would add some docs about it.
