### ISSUE TITLE
Improve documentation regarding AWS ENVS

### ISSUE THREAD

**Issue by sujithpaily** [ivx/yet-another-cloudwatch-exporter#72]
Does yace support IAM user authetication by passing AWS_ACCESS_KEY_ID and SECRET_KEY as enviroment variables?

**Comment by thomaspeitz** [comment]
That should work - @sujithpaily - Could you try out and give me feedback? - Then i would add some docs about it.

**Comment by tyvich** [comment]
Worked for me!
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY

**Comment by sujithpaily** [comment]
It works @thomaspeitz and @tyvich 
cloudwatch-exporter-yace:
        image: 'quay.io/invisionag/yet-another-cloudwatch-exporter:v0.13.6'
        ports:
          - '9105:9106'       
        volumes:
          - /data/prometheus/config-yace.yml:/root/config.yml     
        environment:
          - AWS_ACCESS_KEY_ID=***************
          - AWS_SECRET_ACCESS_KEY=*********************
        container_name: "cloudwatch-exporter-yace"

**Comment by sujithpaily** [comment]
@tyvich 
What all policies should attach to IAM user?

**Comment by tyvich** [comment]
https://github.com/ivx/yet-another-cloudwatch-exporter/blob/master/README.md#iam

Checkout this section of the readme

**Comment by sujithpaily** [comment]
The yace seems using port 5000 . I have changed container port to 5000 and now the container is up and running but getting following errors in log. The IAM policies already attached.

Couldn't describe resources:  RequestError: send request failed
caused by: Post https://tagging.eu-east-1.amazonaws.com/: dial tcp: lookup tagging.eu-east-1.amazonaws.com on 10.1.0.2:53: no such host

**Comment by sujithpaily** [comment]
Getting above error only on discovery configuration. The static configuration is working

**Comment by sujithpaily** [comment]
It was a typo in my conf and its working fine now

**Comment by thomaspeitz** [comment]
Nice aweseom - Closing this issue.
