### ISSUE TITLE
Feature request: Add type ecs

### ISSUE THREAD

**Issue by peimanja** [ivx/yet-another-cloudwatch-exporter#80]
We really would appreciate adding this type. We run many ECS/Fargate and would be amazing to auto discover them.

**Comment by thomaspeitz** [comment]
Hey @peimanja - Added support for ecs/fargate tasks) - Not using this internally so it is hard to test. Would be awesome if you give me some feedback. Thanks and Greetings, Thomas

**Comment by thomaspeitz** [comment]
Thanks. Renamed from ecs to ecs-svc and did not test again. Thanks for finding this. Will fix this today.

**Comment by peimanja** [comment]
> Thanks. Renamed from ecs to ecs-svc and did not test again. Thanks for finding this. Will fix this today.

Did you get a chance to take a look at this?

**Comment by thomaspeitz** [comment]
No sorry @peimanja - Had no time yet. Will debug the next days and tag you here.

**Comment by thomaspeitz** [comment]
@peimanja Still a problem?

**Comment by daviddetorres** [comment]
Hi, 

I made the PR #128 to add support for ECS/ContainerInsights for Fargate metrics support. 

I added a configuration example in the PR.

**Comment by thomaspeitz** [comment]
Closing this as done
