### ISSUE TITLE
multiple statistics metrics 

### ISSUE THREAD

**Issue by alexg84** [ivx/yet-another-cloudwatch-exporter#86]
is this the correct way to create metrics with multiple statistics?
for exmple, I what to see CPUUtilization Minimum, Average and Maximum?

discovery:
  exportedTagsOnMetrics:
    ec2:
      - Name
    ebs:
      - VolumeId
    rds:
      - environment
  ###### RDS Metrics
  jobs:
  - region: us-east-1
    type: "rds"
    searchTags:
      - Key: monitor
        Value: ^true$
    metrics:
      - name: CPUUtilization
        statistics:
        - 'Average'
        period: 60
        length: 300
        - name: CPUUtilization
        statistics:
        - 'Minimum'
        period: 600
        length: 60
        - name: CPUUtilization
        statistics:
        - 'Maximum'
        period: 600
        length: 60
      - name: FreeStorageSpace
        statistics:
        - 'Average'
        period: 60
        length: 300
        - name: FreeStorageSpace
        statistics:
        - 'Minimum'
        period: 600
        length: 60
        - name: FreeStorageSpace
        statistics:
        - 'Maximum'
        period: 600
        length: 60

**Comment by alexg84** [comment]
.

**Comment by thomaspeitz** [comment]
Is this closed intentionally or do you still need help? @alexg84

**Comment by alexg84** [comment]
i figured out and its work now 
thx

**Comment by Zetaku1** [comment]
> i figured out and its work now
> thx

Hello, I know a year has passed,  but could you tell us how you figured it out? It would help me a ton.
Now i'm doing for example:
``` 
statistics:
- Sum
- Average
- Minimum
``` 

But I think it's not working, because metrics stopped showing up.

**Comment by Zetaku1** [comment]
For anyone wondering it works like this:

statistics: [Sum, Average, Minimum]
