### ISSUE TITLE
Aurora metrics are not implemented

### ISSUE THREAD

**Issue by vdczzz** [ivx/yet-another-cloudwatch-exporter#95]
[Aurora RDS CloudWatch metrics](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Monitoring.html#Aurora.Monitoring.RelatedTopics) are not currently searchable. There is some overlap with [RDS CloudWatch metrics](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/MonitoringOverview.html), but it would be preferable to have access to all of them.

e.g.:
```
AuroraBinlogReplicaLag
AuroraGlobalDBReplicatedWriteIO
AuroraGlobalDBDataTransferBytes
AuroraGlobalDBReplicationLag
AuroraReplicaLag
AuroraReplicaLagMaximum
AuroraReplicaLagMinimum
```

...and more.

Thank you!

**Comment by vdczzz** [comment]
misconfig on my part 🤦‍♂

**Comment by wanieldilson** [comment]
What was the fix?
