### ISSUE TITLE
Migrate to GetMetricData api calls and reduce listMetricsRequests

### ISSUE THREAD

**Issue by bheight-Zymergen** [ivx/yet-another-cloudwatch-exporter#96]
I've recently pulled down the latest changes that have been added and with the same configuration as I had before I'm now getting throttled:

```
panic: Throttling: Rate exceeded
        status code: 400, request id: cad3e71a-687a-4406-ac9a-e5b9021bd347

goroutine 351 [running]:
main.getMetricsList(0xc000870210, 0x1, 0x1, 0xc0002bb090, 0xc000234b40, 0x17, 0xc0001f5fc0, 0x1, 0x1, 0x0, ...)
        /opt/aws_cloudwatch.go:260 +0x191
main.scrapeDiscoveryJob.func2(0xc0002bb000, 0xc0004dd4c0, 0xc0001725a0, 0xc3c200, 0xc0002c0020, 0xc0002e0100, 0xc000664800, 0x13, 0x20, 0xc000332320, ...)
        /opt/abstract.go:150 +0xd4
created by main.scrapeDiscoveryJob
        /opt/abstract.go:146 +0x451
```

This wasn't as issue before commit: 1b81d6720f9a7f09871211ea6f6bb22bcde1b5ac

Changes since then: https://github.com/ivx/yet-another-cloudwatch-exporter/compare/1b81d6720f9a7f09871211ea6f6bb22bcde1b5ac...master

**Comment by bheight-Zymergen** [comment]
I've kind of reach the point at which I think using `GetMetricData` is going to really be the only way I'll be able to get this exporter to work for me given the number of metrics and number of instances I'm querying against.

Are there any plans to use GetMetricData for bulk API calls?

**Comment by thomaspeitz** [comment]
How many metrics do you have?

**Comment by bheight-Zymergen** [comment]
We've had to scale back what we were gathering from CW significantly (even after getting our API call quota increased by AWS). 

As of right now our environment for yace looks like this:

- RDS we are scraping 45 instance from CW for ~46 CW Metrics
- ALB we are scraping 28 instances from CW for ~10 CW Metrics -- Plus the associated Target Groups
- ELB we are scraping 14 instance from CW for ~6 CW Metrics

Even with the API quota increased by AWS we regularly see throttling happen which then leaves gaps in the time series. 

We'd like to add NLB's, Lambdas, and a few others but at the moment we can't as a result of the throttling. Bulk collection of metrics using GetMetricData would significantly reduce the number of API calls we are making which would allow us to scale properly.

**Comment by bheight-Zymergen** [comment]
It actually seems like there are two places I'm being throttled at.

One being the GetMetricStatistics and the other at `ListMetricsRequest` which has a maximum of 25 transactions per second.

**Comment by thomaspeitz** [comment]
Thanks for the insights. Will dig this down on Friday. Will try to add so many metrics in our collector till i get the problem as well.

**Comment by thomaspeitz** [comment]
How often do you scrape? - Did you try out to set this to like 1m (i know a lot of people scrape every 15 seconds) @bheight-Zymergen

**Comment by thomaspeitz** [comment]
I think a move to `GetMetricData` would make totally sense but this would be a major refactoring of the whole project as things must be done completely different to do it nicely. Afraid of the development time currently. Will timebox this for two hours at the weekend and see how far i am able to get.

**Comment by thomaspeitz** [comment]
Docs: 
- https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricData.html

Started my work but not much time today to get it running.
https://github.com/ivx/yet-another-cloudwatch-exporter/pull/101

Having another big project currently. Moving into a new flat next week. So could be a little bit boring here the next days. But it is on my roadmap. Read a lot over the api and i think it will be a hard cut to the way the exporter currently works but it it is worth it. Especially in terms of costs. I think our company will add a lot more metrics to prometheus if it is cheaper in the future. So maybe i can do some work there as well. Currently doing a lot in my free time.

Greetings, Thomas

**Comment by bheight-Zymergen** [comment]
> How often do you scrape? - Did you try out to set this to like 1m (i know a lot of people scrape every 15 seconds) @bheight-Zymergen

Sorry for the delayed response I was on vacation in an area with no coverage.

Our scrape job for metrics is every 60 seconds.

**Comment by bheight-Zymergen** [comment]
https://github.com/ivx/yet-another-cloudwatch-exporter/pull/118 

Looks like someone got around to this before I finished up mine.
