### ISSUE TITLE
cross account access with accesss and secret key

### ISSUE THREAD

**Issue by polganesh** [ivx/yet-another-cloudwatch-exporter#99]
Hi,
I am trying to check if this exporter can be used for cross account with access and secret key. it will be great if we are having example for same.

**Comment by thomaspeitz** [comment]
Hey,

i think it should work with `roleArn` setting. See README.md where to set it for static / discovery jobs. 

But not 100% sure how your setup looks like. Maybe you can explain it a little bit more.

Greetings, Thomas

**Comment by thomaspeitz** [comment]
@polganesh ping :)

**Comment by polganesh** [comment]
i am trying to use  this as a helm chart but not sure how to attach role to k8s cluster.

**Comment by thomaspeitz** [comment]
Closing due to very old issue. Please tag me if this is still a problem. Then i reopen it.
